docs: button design change and add button in hero of designkit page
nuxt/framework pull request #10139
Opened 2023-01-17 11:02 UTC by CarolinaDelerue

2023-01-17 14:55 UTC, Flosciante requested changes

2023-01-17 14:55 UTC, Flosciante commented on docs/content/design-kit.md
> +    trailing: 'trailing'
You can put this props directly on `::PageHero` after adding the buttons on `PageHero` component. (nuxtlabs/nuxt.com#1052)

2023-01-18 16:16 UTC, Flosciante requested changes

2023-01-18 16:16 UTC, Flosciante commented on docs/content/3.showcase.md
> +hidden: true
Don't forget to update when you will have changed the names in the PR of nuxt.com (nuxtlabs/nuxt.com#1052)

2023-01-18 16:16 UTC, Flosciante commented on docs/content/3.showcase.md
> +    to: "https://chrome.google.com/webstore/detail/vue-telescope/neaebjphlfplgdhedjdhcnpjkndddbpd"
Simple quote

2023-01-19 09:39 UTC, Flosciante approved these changes

2023-01-20 10:05 UTC, clemcode requested changes
TODO @clemcode : Revert yarn.lock

2023-01-20 14:10 UTC, clemcode approved these changes

2023-01-20 14:11 UTC, merged