docs: add migration guide for bridge composition api
nuxt/framework pull request #1669
Opened 2021-11-03 16:22 UTC by danielroe

### 🔗 Linked issue

resolves #1321

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This is an initial migration guide for moving from `@nuxtjs/composition-api` to Nuxt Bridge composables.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.
- [ ] Update https://github.com/nuxt-community/composition-api docs as well

2021-11-03 16:42 UTC, pi0 commented on docs/content/1.getting-started/4.composition-api.md
> +   + import { useContext } from '@nuxtjs/composition-api`
With bridge, we can directly advice to import from `#app` or `vue`

2021-11-03 16:42 UTC, pi0 commented on docs/content/1.getting-started/4.composition-api.md
> +If you migrate to a Nuxt 3-style plugin, note that a plugin takes only one argument (`nuxtApp`). You can find out more in [the Nuxt 3 plugin docs](/docs/directory-structure/plugins).
It would be nice to put this option above, encouraging to use Nuxt 3 plugin and legacy only if there is a need for

2021-11-03 16:42 UTC, pi0 commented on docs/content/1.getting-started/4.composition-api.md
> +This `useMeta` composable uses `@vueuse/head` under the hood (rather than `vue-meta`) to manipulate your `<head>`. Accordingly, it is recommended not to use both the native Nuxt 2 `head()` properties
While it is nice we are suggesting for migration, we need to also provide `@nuxtjs/composition-api` replacement with vue-meta `useNuxtApp().$meta` as a second option. vueuse is not implementing all of those features.

2021-11-03 16:42 UTC, pi0 commented on docs/content/1.getting-started/4.composition-api.md
> +# Migrating to Bridge Composition API
IMO slug need to also include bridge to avoid confusing with nuxt 3 capi

2021-11-03 17:33 UTC, antfu commented on docs/content/1.getting-started/4.bridge-composition-api.md
> +If you have been using just `@vue/composition-api` and not using the Nuxt community library, then things are very straightforward.
```suggestion
If you have been using just `@vue/composition-api` and not `@nuxtjs/composition-api`, then things are very straightforward.
```

I guess it might be clear to state the package name before it has been mentioned. Or it might be better to flip these sections to talk about `@nuxtjs/composition-api` first

2021-11-03 21:08 UTC, DamianGlowala requested changes

2021-11-03 21:08 UTC, DamianGlowala commented on packages/bridge/src/runtime/capi.legacy.mjs
> +export const reqRef = unsupported('`reqRef` is a deprecated method that is no longer provided  and can be replaced with `ref` (import from `@vue/composition-api`).')
contains double space after the phrase _is no longer provided (...)_

2021-11-03 22:07 UTC, danielroe commented on docs/content/1.getting-started/4.bridge-composition-api.md
> +Nuxt Bridge provides access the Composition API syntax. It is specifically designed to be aligned with Nuxt 3. Because of this, there are a few extra steps to take when enabling Nuxt Bridge, if you h
```suggestion
Nuxt Bridge provides access to the Composition API syntax. It is specifically designed to be aligned with Nuxt 3. Because of this, there are a few extra steps to take when enabling Nuxt Bridge, if you have been using the Composition API previously.
```

2021-11-03 22:07 UTC, danielroe commented on docs/content/1.getting-started/4.bridge-composition-api.md
> +1. First, remove the plugin where you are manually registering the composition API. Nuxt Bridge will handle this for you.
```suggestion
1. First, remove the plugin where you are manually registering the Composition API. Nuxt Bridge will handle this for you.
```

2021-11-03 22:08 UTC, danielroe commented on docs/content/1.getting-started/4.bridge-composition-api.md
> +Nuxt Bridge implements the composition API slightly differently from `@nuxtjs/composition-api` and provides different composables (designed to be aligned with the composables that Nuxt 3 provides).
```suggestion
Nuxt Bridge implements the Composition API slightly differently from `@nuxtjs/composition-api` and provides different composables (designed to be aligned with the composables that Nuxt 3 provides).
```

2021-11-03 22:08 UTC, danielroe commented on packages/bridge/src/runtime/capi.legacy.mjs
> +export const reqRef = unsupported('`reqRef` is a deprecated method that is no longer provided  and can be replaced with `ref` (import from `@vue/composition-api`).')
```suggestion
export const reqRef = unsupported('`reqRef` is a deprecated method that is no longer provided and can be replaced with `ref` (import from `@vue/composition-api`).')
```

2021-11-04 11:10 UTC, danielroe commented on docs/content/1.getting-started/3.bridge.md
> +If you was previusly using `@vue/composition-api` or `@nuxtjs/composition-api`, please read [composition api migration guide](/getting-started/bridge-composition-api).
```suggestion
If you were previusly using `@vue/composition-api` or `@nuxtjs/composition-api`, please read the [composition api migration guide](/getting-started/bridge-composition-api).
```

2021-11-04 11:11 UTC, danielroe commented on docs/content/1.getting-started/3.bridge.md
> +You will also need to enable feature explicitly in your `nuxt.config`:
```suggestion
You will also need to enable this feature explicitly in your `nuxt.config`:
```

2021-11-04 11:11 UTC, danielroe commented on docs/content/1.getting-started/3.bridge.md
> +Nuxt Bridge provides identical features of Nuxt 3 ([docs](/docs/usage)) but there are some limitations notably `useAsyncData` and `useFetch` composables are not available. Please read rest of this pa
```suggestion
Nuxt Bridge provides identical features of Nuxt 3 ([docs](/docs/usage)) but there are some limitations, notably that `useAsyncData` and `useFetch` composables are not available. Please read rest of this page for details.
```

2021-11-04 11:13 UTC, danielroe commented on docs/content/1.getting-started/3.bridge.md
> +Nuxt Bridge provides identical features of Nuxt 3 ([docs](/docs/usage)) but there are some limitations, notably that `useAsyncData` and `useFetch` composables are not available. Please read the rest
```suggestion
Nuxt Bridge provides identical features to Nuxt 3 ([docs](/docs/usage)) but there are some limitations, notably that `useAsyncData` and `useFetch` composables are not available. Please read the rest of this page for details.
```

2021-11-04 11:13 UTC, danielroe commented on docs/content/1.getting-started/3.bridge.md
> +You can now migrate to Nuxt 3-style plugins API, which are slightly different in format than Nuxt 2.
```suggestion
You can now migrate to the Nuxt 3-style plugins API, which is slightly different in format from Nuxt 2.
```

2021-11-04 11:13 UTC, danielroe commented on docs/content/1.getting-started/3.bridge.md
> +Nuxt Bridge provides an new Nuxt 3 meta API that can be accessed with a new `useMeta` composable.
```suggestion
Nuxt Bridge provides a new Nuxt 3 meta API that can be accessed with a new `useMeta` composable.
```

2021-11-04 11:14 UTC, danielroe commented on docs/content/1.getting-started/3.bridge.md
> +    // meta: false,
```suggestion
    // meta: true,
```

2021-11-04 11:15 UTC, danielroe commented on docs/content/1.getting-started/4.bridge-composition-api.md
> +In order to use vue-meta, you can continue importing `useMeta` from `@nuxtjs/composition-api`, which is shimmed by Nuxt Bridge.
```suggestion
In order to use vue-meta, you can continue importing `useMeta` and `defineComponent` from `@nuxtjs/composition-api`, which is shimmed by Nuxt Bridge.

However, note that the existing limitations of `useMeta` continue, so it cannot be used in `<script setup>` and you must include a `head: {}` object within your `defineComponent`.

```js
import { defineComponent, useMeta } from '@nuxtjs/composition-api'

export default defineComponent({
  // You need to define an empty head to activate this functionality
  head: {},
  setup() {
    // This will allow you to set the title in head - but won't allow you to read its state outside of this component.
    const { title } = useMeta()
    title.value = 'My page'
  },
})
```
```

2021-11-04 11:20 UTC, merged