feat(nuxt3, bridge): add lazy helpers (`useLazyAsyncData` and `useLazyFetch`)
nuxt/framework pull request #1861
Opened 2021-11-11 12:40 UTC by danielroe

### 🔗 Linked issue

resolves #1688, resolves #1831

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR:
 * renames `defer` to `lazy` within the `useAsyncData` and `useFetch` composables
 * adds new `useLazyAsyncData` and `useLazyFetch` as aliases for `lazy: true` versions of these composables
 * exposes these within Nuxt Bridge
 * adds `onServerPrefetch` to `useAsyncData` for Nuxt 2 support
 * adds documentation for `default` option
 * adds composition api migration docs

~~**Note**: there is a (separate) issue with typing for these composables within Bridge as `Ref` is being imported from `vue` - still thinking of how to solve 🤔~~

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.
- [x] solve typing in Nuxt Bridge

2021-11-11 20:46 UTC, DamianGlowala requested changes

2021-11-11 20:46 UTC, DamianGlowala commented on docs/content/3.docs/1.usage/1.data-fetching.md
>    * _server_: whether the fetch the data on server-side (defaults to `true`)
* _server_: whether **to** fetch the data on server-side (defaults to `true`)

2021-11-11 20:47 UTC, danielroe commented on docs/content/3.docs/1.usage/1.data-fetching.md
>    * _server_: whether the fetch the data on server-side (defaults to `true`)
```suggestion
  * _server_: whether to fetch the data on server-side (defaults to `true`)
```

2021-11-15 12:08 UTC, pi0 approved these changes

2021-11-15 12:09 UTC, merged