docs(examples): Add extend-routes example
nuxt/framework pull request #2057
Opened 2021-11-21 11:42 UTC by Atinux

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)

### 📚 Description

Since vue-router 4 has the `addRoute` method, I believe adding routes at runtime is quite interesting.
We can discuss about merging this example with https://github.com/nuxt/framework/tree/main/examples/module-extend-pages to showcase the two possibilities.

Once done, and adding the examples section (#1960), we will be able to improve the documentation about routing 😊 

### 📝 Checklist

- [ ] There is an hydration error happening when hitting a route coming from SSR, any help on this would be much appreciated @posva 

https://user-images.githubusercontent.com/904724/142760337-b35ee82b-901d-459b-a43f-3f25bd460a41.mp4

To run the example locally (read https://github.com/nuxt/framework#-development first):
```bash
yarn example extend-routes
```

2021-11-21 12:04 UTC, pi0 commented on examples/extend-routes/plugins/extend-routes.ts
> +  $router.addRoute({
It would be nice if we add `addRoute` auto import from pages module. Making this simpler and less prune to errors

2021-11-21 12:06 UTC, pi0 commented
Can you please use documentation to better explain purpose is for runtime dynamic routes addition? Current example is adding a route in all conditions, lacking a real world use

2021-11-21 12:19 UTC, Atinux commented
One example is the ability to add routes for localised website, I think that's what @loick was looking for to use in BackMarket website.

2021-11-21 12:21 UTC, Atinux commented on examples/extend-routes/plugins/extend-routes.ts
> +  $router.addRoute({
I was looking at how we could have it but cannot find, do you have a clue where/how to add this?

I tester and `useRouter()` returns `undefined` in Nuxt plugins.

2021-11-21 12:22 UTC, Atinux commented
Some context in Nuxt v2: https://github.com/nuxt/nuxt.js/issues/9594

2021-11-21 12:26 UTC, pi0 commented
Seems a nice example using either localized condition, feature flags or context user.

2021-11-21 12:33 UTC, DamianGlowala requested changes

2021-11-21 12:33 UTC, DamianGlowala commented on examples/extend-routes/README.md
> +This example showcase how to add routes at runtime using [`router.addRoute()`](https://next.router.vuejs.org/guide/advanced/dynamic-routing.html#adding-routes) method from [vue-router](https://next.r
This example showcase**s** (...)

2021-11-21 12:33 UTC, DamianGlowala commented on examples/extend-routes/README.md
> +Play online on [StackBliz](https://stackblitz.com/github/nuxt/framework/tree/main/examples/extend-routes)
- StackBliz -> StackBli**t**z
- Missing full stop ending the sentence

2021-11-21 12:37 UTC, pi0 commented on examples/extend-routes/README.md
> +Play online on [StackBliz](https://stackblitz.com/github/nuxt/framework/tree/main/examples/extend-routes)
Thanks! Small tip you can use <kbd>ctrl+g</kbd> to directly add change suggestion:

<img width="245" alt="image" src="https://user-images.githubusercontent.com/5158436/142762074-3a4648e7-b815-4f18-b583-0206f34947f9.png">

2021-11-21 12:37 UTC, pi0 commented on examples/extend-routes/README.md
> +Play online on [StackBliz](https://stackblitz.com/github/nuxt/framework/tree/main/examples/extend-routes)
```suggestion
Play online on [StackBlitz](https://stackblitz.com/github/nuxt/framework/tree/main/examples/extend-routes)
```

2021-11-21 12:37 UTC, pi0 commented on examples/extend-routes/README.md
> +This example showcase how to add routes at runtime using [`router.addRoute()`](https://next.router.vuejs.org/guide/advanced/dynamic-routing.html#adding-routes) method from [vue-router](https://next.r
```suggestion
This example showcases how to add routes at runtime using [`router.addRoute()`](https://next.router.vuejs.org/guide/advanced/dynamic-routing.html#adding-routes) method from [vue-router](https://next.router.vuejs.org).
```

2021-11-21 12:41 UTC, DamianGlowala commented on examples/extend-routes/README.md
> +Play online on [StackBliz](https://stackblitz.com/github/nuxt/framework/tree/main/examples/extend-routes)
Oh, that will make it more convenient, didn't know that - thanks! (:

2021-11-21 20:07 UTC, posva commented on examples/extend-routes/plugins/extend-routes.ts
> +  $router.addRoute({
it looks like you are adding the route after the router is used by app with `app.use(router)` which triggers the initial navigation on the client to a still non existent route.
That is okay, but ideally, some navigation guard should detect that the route must be added dynamically, add the route, and then trigger a new navigation with `next(to.fullPath)` or by returning the location.

2021-12-26 12:14 UTC, Nirlah commented
For reference, the plugin `addRoute` approach causes an hydration error #2475

2022-03-11 09:02 UTC, pi0 commented
Moving to #3600 to add example when feature lands.

2022-03-11 09:02 UTC, closed without merging