docs(example): Add Supabase integration example
nuxt/framework pull request #2058
Opened 2021-11-21 12:16 UTC by Atinux

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)

### 📚 Description

This example showcases how to use [Supabase](https://supabase.com) with [Nuxt](https://v3.nuxtjs.orgs).

## Features

- `useSupabase()` composable
- User sessions with SSR support
- Handle auth changes (and removes the session)

2021-11-21 12:21 UTC, pi0 commented on examples/integrations-supabase/nuxt.config.ts
> +      url: process.env.SUPABASE_URL,
Key shall be same as env name to allow overriding un runtime

2021-11-21 12:21 UTC, pi0 commented on examples/integrations-supabase/package.json
> +    "@nuxthq/ui": "npm:@nuxthq/ui-edge@latest",
TODO: we need to move it to nuxt/ui first

2021-11-21 12:22 UTC, pi0 commented on examples/integrations-supabase/plugins/supabase.server.ts
> +  user.value = (await auth.api.getUserByCookie(req)).user
This logic can be handle on demand in composable without using a global plugin (unless global guard is the purpose)

2021-11-21 12:23 UTC, pi0 commented on examples/integrations-supabase/server/api/supabase/session.ts
> +  supabase.auth.api.setAuthCookie(req, res)
I believe this can also be handled in app namespace (ssr only) instead of adding an additional api route

2021-11-21 12:39 UTC, DamianGlowala requested changes

2021-11-21 12:39 UTC, DamianGlowala commented on examples/integrations-supabase/README.md
> +- Handle auth changes (and removes the session)
I would suggest rewording to:

Handle auth changes (and remov**ing** the session)

2021-11-21 12:39 UTC, DamianGlowala commented on examples/integrations-supabase/README.md
> +Start the development server on http://localhost:3000
Missing colon at the end:

Start the development server on http://localhost:3000:

2021-11-21 13:42 UTC, DamianGlowala requested changes

2021-11-21 13:42 UTC, DamianGlowala commented on examples/integrations-supabase/README.md
> +Start the development server on http://localhost:3000
```suggestion
Start the development server on http://localhost:3000:
```

2021-11-21 13:42 UTC, DamianGlowala commented on examples/integrations-supabase/README.md
> +- Handle auth changes (and removes the session)
I would suggest either of the following:
- Handle**s** auth changes (and removes the session)
- Handl**ing** auth changes (and remov**ing** the session)

2021-11-21 13:42 UTC, DamianGlowala commented on examples/integrations-supabase/README.md
> +Make sure to install the dependencies and setup the `.env`.
```suggestion
Make sure to install the dependencies and setup the `.env`:
```

2021-11-21 23:08 UTC, Atinux commented on examples/integrations-supabase/server/api/supabase/session.ts
> +  supabase.auth.api.setAuthCookie(req, res)
Well actually when doing the login it needs to also call our server to store the cookie as secured. How to would want to handle it without calling back the server?

Or we need to have a saveSession() exposed from Nuxt to easily create HTTP only cookies for secured sessions experience from day 1

2021-11-21 23:12 UTC, Atinux commented on examples/integrations-supabase/plugins/supabase.server.ts
> +  user.value = (await auth.api.getUserByCookie(req)).user
Well actually having it by default offers a lot of features directly (feature flags per user, redirects, etc).

But if Nuxt exposes a smarter way to cachify() the user to speed up the process that would be neat.

I need to time the time execution of the plugin.

Something that Nuxt itself should expose (through hooks) so we can display them in the devtools (performance tabs)

2021-11-21 23:12 UTC, Atinux commented on examples/integrations-supabase/package.json
> +    "@nuxthq/ui": "npm:@nuxthq/ui-edge@latest",
Let's get an estimate date for it :)

2021-11-21 23:16 UTC, Atinux commented on examples/integrations-supabase/nuxt.config.ts
> +      url: process.env.SUPABASE_URL,
Not sure to understand, what feature does it bring?

2021-11-21 23:17 UTC, Atinux commented on examples/integrations-supabase/README.md
> +Start the development server on http://localhost:3000
It feels weird to me to add the : at the end

2021-11-21 23:18 UTC, Atinux commented on examples/integrations-supabase/README.md
> +Start the development server on http://localhost:3000
What do you think @danielroe ?

2021-11-21 23:36 UTC, sduduzog commented
This is so awesome. I've been trying to experiment with ways to try add SSR support to https://github.com/supabase-community/nuxt-supabase with no luck but I'll definitely take learnings here and work on a PR there.

2021-11-22 02:03 UTC, pi0 commented on examples/integrations-supabase/nuxt.config.ts
> +      url: process.env.SUPABASE_URL,
Overriding env variables at **runtime**. Current config basically adds env on build-time to bundle. Check this: https://github.com/nuxt/framework/blob/d68318f9d5ee25f6377edb866cd1b5846e8bfdce/packages/nitro/src/runtime/app/config.ts#L7

2021-11-22 02:03 UTC, pi0 commented on examples/integrations-supabase/package.json
> +    "@nuxthq/ui": "npm:@nuxthq/ui-edge@latest",
If not ready soon, we shall remove UI components, same as other examples but I guess initial version should be ready by next week.

2021-11-22 02:04 UTC, pi0 commented on examples/integrations-supabase/plugins/supabase.server.ts
> +  user.value = (await auth.api.getUserByCookie(req)).user
Not quite sure to understand what you mean but yes we can cache promise within a composable/context :)

2021-11-22 02:06 UTC, pi0 commented on examples/integrations-supabase/server/api/supabase/session.ts
> +  supabase.auth.api.setAuthCookie(req, res)
Sure we probaly need `useSession`. My main point is that it can be in a composable and yet running in server-only to set secure cookie. This reduces boilerplate and allows logic working with rest of ssr context.

2021-11-22 02:06 UTC, pi0 commented on examples/integrations-supabase/README.md
> +Start the development server on http://localhost:3000
This convention can also potentially make formatting issues. If we do decide to add `:`, should use explicit markdown syntax for generated link or add a space after 3000

2021-11-22 08:21 UTC, Atinux commented on examples/integrations-supabase/server/api/supabase/session.ts
> +  supabase.auth.api.setAuthCookie(req, res)
You need to try the demo to understand, when using Supabase, you basically no need to create API routes.

So I don't see how you want to implement this without an API call to works.

2021-11-22 08:26 UTC, Atinux commented on examples/integrations-supabase/nuxt.config.ts
> +      url: process.env.SUPABASE_URL,
What would be the purpose of changing these keys at runtime? Do you have an example?

2021-11-22 10:16 UTC, pi0 commented on examples/integrations-supabase/nuxt.config.ts
> +      url: process.env.SUPABASE_URL,
it is runtime config :) Changing config without need to rebuild

2021-11-22 10:17 UTC, pi0 commented on examples/integrations-supabase/server/api/supabase/session.ts
> +  supabase.auth.api.setAuthCookie(req, res)
Same server logic just in composable :) Will make refactor

2021-11-22 13:11 UTC, larbish requested changes

2021-11-22 13:11 UTC, larbish commented on examples/integrations-supabase/composables/useSupabase.ts
> +      // Check if user is authenticated on client-side
```
      // Check if user is authenticated on client-side
      const session = supabase.auth.session()
      if (session) {
        // Set cookie on server-side
        setServerSession('SIGNED_IN', session)
        user.value = supabase.auth.user()
      }
```

This part of code can be removed. Cookie are already set on server side by `supabase.auth.onAuthStateChange()`

2021-12-01 12:00 UTC, eMeRiKa13 commented
Thanks a lot for this code. It's very helpful. 

Could you add an example of how to query Supabase in a page, (other to the authenticated user) please?

`supabase.from("my_table").select('*').eq(...)`

I'm trying to use the useSupabase() composable to do that but I can't make it work.

2022-02-03 11:23 UTC, pi0 commented
Finally moving this to a Nuxt module. https://github.com/larbish/supabase-module/issues/8

2022-02-03 11:23 UTC, closed without merging