feat(nuxt3,bridge): add automatic schema augmentation declaration
nuxt/framework pull request #3096
Opened 2022-02-07 10:41 UTC by danielroe

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds a new `schema.d.ts` declaration file for augmenting the schema. With this change, modules do not need to declare their own type augments.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2022-02-07 10:58 UTC, pi0 requested changes

2022-02-07 10:58 UTC, pi0 commented on packages/bridge/src/app.ts
> +    src: ''
(is this typing issue? Would be nice to be fixed at some point :D)

2022-02-07 10:58 UTC, pi0 commented on packages/nuxt3/src/core/nuxt.ts
> +      await installModule(m, {})
Refactor: If `installModule` could directly return `{ meta }`, we can create an array of installed modules meta usable for hooks and remove the dependency between `templates` and kit utils for normalizing config modules! (this also allows to register types for modules dynamically installed by another module)

2022-02-07 12:46 UTC, pi0 commented on packages/nuxt3/src/core/templates.ts
> +    })).filter(m => m.configKey && m.name && !adHocModules.includes(m.name))
- Shouldn't `meta.name` prioritize over `entryPath` for name?
- Why don't do normalization in `addModule` itself? `isAdhoc` flag could also be inferred in kit from name (templates should ideally have less logic)
-

2022-02-07 12:46 UTC, pi0 commented on packages/bridge/src/app.ts
> +    const meta = await normalizeModule(m).then(([m]) => m.getMeta?.())
Maybe we can use `moduleContainer.requiredModules` to natively access installed nuxt 2 modules instead?

2022-02-07 12:50 UTC, danielroe commented on packages/nuxt3/src/core/templates.ts
> +    })).filter(m => m.configKey && m.name && !adHocModules.includes(m.name))
Example:

```js
import { defineNuxtConfig } from 'nuxt3'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  modules: ['~/modules/test'],
})
```

And:
```js
import { defineNuxtModule } from '@nuxt/kit'

const defaults = {
  foo: true,
}

export default defineNuxtModule({
  meta: {
    name: 'bingle',
    configKey: 'bingleBob',
  },
  defaults,
})
```

As is, we want to augment the module entry path rather than the name of the module, to support local modules (and there may be other reasons too where a module's name doesn't equal a requirable/importable entity).

2022-02-07 12:57 UTC, danielroe commented on packages/bridge/src/app.ts
> +    const meta = await normalizeModule(m).then(([m]) => m.getMeta?.())
Hm. That would be nice. But isn't this code running before that is populated?

2022-02-07 13:04 UTC, pi0 commented on packages/nuxt3/src/core/templates.ts
> +    })).filter(m => m.configKey && m.name && !adHocModules.includes(m.name))
`importName` seems better but shall we only rely on `m.entryPath` then? `meta.name` is not necessarily a valid import path either without considering typescript resolving same as `resolveModule`. We could expose resolved `entryPath` from [here](https://github.com/nuxt/framework/blob/3598d50b8ceb7d362b5b77aadacacb25d17e8c6a/packages/kit/src/module/install.ts#L20)

2022-02-07 13:06 UTC, pi0 commented on packages/bridge/src/app.ts
> +    const meta = await normalizeModule(m).then(([m]) => m.getMeta?.())
Using `modules:done` seems a good idea! It would be nice if we avoid exposing extra `normalizeModule` from kit and have standalone Nuxt2 implementation if we want to support it. (module builder also populate interface therefore is not a big loss for bridge users)

2022-02-07 13:12 UTC, danielroe commented on packages/nuxt3/src/core/templates.ts
> +    })).filter(m => m.configKey && m.name && !adHocModules.includes(m.name))
TS is able to follow the aliasing as we do configure it to do so in `tsconfig.json`. But may be worth exposing resolved path for other purposes 👍.

As far as fallback to `meta.name`, this is mostly useful for directly installed modules (e.g. this kind of thing: https://github.com/nuxt/framework/blob/baa0853afa230ca9c4bdabb7db2b98275f59fcc8/packages/bridge/src/setup.ts#L15). If `meta.name` isn't a valid import path, TS will cope - so there seems to be no downside.

2022-02-08 18:52 UTC, pi0 approved these changes

2022-02-08 19:09 UTC, merged