feat(pages): Default scroll behavior
nuxt/framework pull request #3851
Opened 2022-03-23 01:12 UTC by joel-wenzel

### 🔗 Linked issue

[Discussion #3338](https://github.com/nuxt/framework/discussions/3338)

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Added new hook for `page:transition:finish` emitted from NuxtPage. Hook fires after the vue transition `afterLeave` event.
Hook also triggers if the page has no transition when suspense resolves.

Also added default scroll behavior, which can still be overridden by using `app/router.options`

### 📝 Checklist

- [ x] I have linked an issue or discussion.
- [ x] I have updated the documentation accordingly.

2022-03-29 08:52 UTC, posva commented on packages/nuxt3/src/pages/routing/default-router.options.ts
> +      setScrollRestoration('auto')
I don't think you need this whole block as the router already handles on load scroll

2022-03-29 08:52 UTC, posva commented on packages/nuxt3/src/pages/routing/default-router.options.ts
> +            hash = '#' + window.CSS.escape(hash.substr(1))
I think you can go much simpler 🙂 
The router already tries to handle most scenarios: https://github.com/vuejs/router/blob/main/src/scrollBehavior.ts#L77

2022-03-29 08:52 UTC, posva commented on packages/nuxt3/src/pages/routing/default-router.options.ts
> +                selector: hash,
`selector` was deprecated in favor of `el`

2022-03-29 08:52 UTC, posva commented on packages/nuxt3/src/pages/runtime/page.ts
> +          _wrapIf(Transition, getTransitionProps(routeProps),
Here you are always wrapping with Transition but this is not always desired

2022-03-31 00:02 UTC, joel-wenzel commented on packages/nuxt3/src/pages/routing/default-router.options.ts
> +            hash = '#' + window.CSS.escape(hash.substr(1))
@posva Cleaned that up. The only thing that seemed like it wasn't handled was `scrollMarginTop` so I left that in.

2022-03-31 00:04 UTC, joel-wenzel commented on packages/nuxt3/src/pages/runtime/page.ts
> +          _wrapIf(Transition, getTransitionProps(routeProps),
@posva Going through the _wrapIf it should only render the Transition component if the transition props are truthy unless I am missing something

2022-03-31 08:25 UTC, posva commented on packages/nuxt3/src/pages/runtime/page.ts
> +          _wrapIf(Transition, getTransitionProps(routeProps),
I will check again, I read the diff a bit too quickly

2022-04-22 15:24 UTC, pi0 commented
@joel-wenzel sorry, your PR got stalled. Can you please consider rebasing it?

@posva Can you please confirm if this changes are looking good to you or any change needed?

2022-04-30 21:10 UTC, fanckush commented
Merging this PR would fix the issue #2817 btw

2022-05-08 03:40 UTC, vis97c requested changes

2022-05-08 03:40 UTC, vis97c commented on packages/nuxt3/src/pages/routing/default-router.options.ts
> +    const isRouteChanged = to !== from
Please support for cases were the only difference is the hash (anchor links), in those cases the scroll should be handled by the browser and not reseted every time.

I was going to add it as an issue but since there is a pending MR i think is best to have it here.

2022-05-09 22:58 UTC, joel-wenzel commented
> @joel-wenzel sorry, your PR got stalled. Can you please consider rebasing it?

@pi0 No problem. Rebased. Should be all good now

2022-05-09 23:30 UTC, joel-wenzel commented on packages/nuxt3/src/pages/routing/default-router.options.ts
> +    const isRouteChanged = to !== from
@vis97c Can you provide a reproduction of the use case you are trying to solve/avoid or elaborate a little further? 
I pushed a change to handle anchor tag navigation when on the same page and it works I as I would expect. 

Returning nothing from scroll behavior for those scenarios doesn't delegate anything to the browser. I could be missing something though

2022-05-10 13:58 UTC, vis97c commented on packages/nuxt3/src/pages/routing/default-router.options.ts
> +    const isRouteChanged = to !== from
Yeah sure. Not sure if it needs reproduction but using anchor links on a page triggers a router update.

```html
<a href="#about">about</a>
<div id="about"></div>
```

When clicking the link the page should be scrolling to whatever position "#about" div I located but the current approach would reset the scroll to 0 preventing that from happening. Let me know if the example is not clear enough so I can implement a reproduction.

2022-05-10 22:26 UTC, joel-wenzel commented on packages/nuxt3/src/pages/routing/default-router.options.ts
> +    const isRouteChanged = to !== from
That scenario is handled here for sure. This is my third test page:
```html
<div>
    <a href="#hash">Hash</a>
    <a href="#hash2">Hash2</a>
    <div style="padding-top: 2000px">
      child child page
    </div>
    <h6 id="hash" style="scroll-margin-top: 50px;">
      Should go here
      <a href="#hash2">Hash2</a>
    </h6>
    <h6 id="hash2" style="scroll-margin-top: 50px; margin-top: 500px">
      Should go here
    </h6>
    <p style="margin-bottom: 2000px">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis, modi quis dolorum asperiores impedit aspernatur nam! Aut illo explicabo eligendi rem consequuntur quam! Esse cupiditate officiis ullam nihil laudantium porro.
    </p>
  </div>
```

2022-05-21 14:16 UTC, joel-wenzel commented
@pi0 I merged instead of rebase. If you would rather I make a new branch/PR let me know

2022-06-16 09:10 UTC, fanckush commented
bump

2022-06-16 09:29 UTC, Rigo-m commented
> When will it be merged? Current Nuxt 3 page link behaviour is counter-intuitive because page sticks on current position of previous page.
> 
> Update 2022-06-04: When playing around with Content Wind I noticed that scroll behaviour was as expected. So I checked for a custom router configuration et voila:
> 
> ```
> import type { RouterConfig } from '@nuxt/schema'
> 
> // https://router.vuejs.org/api/#routeroptions
> export default <RouterConfig>{
>   scrollBehavior (to, _, savedPosition) {
>     const nuxtApp = useNuxtApp()
> 
>     // If history back
>     if (savedPosition) {
>       // Handle Suspense resolution
>       return new Promise((resolve) => {
>         nuxtApp.hooks.hookOnce('page:finish', () => {
>           setTimeout(() => resolve(savedPosition), 50)
>         })
>       })
>     }
>     // Scroll to heading on click
>     if (to.hash) {
>       setTimeout(() => {
>         const heading = document.querySelector(to.hash) as any
> 
>         return window.scrollTo({
>           top: heading.offsetTop,
>           behavior: 'smooth'
>         })
>       })
>       return
>     }
> 
>     // Scroll to top of window
>     return { top: 0 }
>   }
> }
> ```
> 
> This might also solve your problems with latest plain Nuxt 3 apps.

The problem of this, at least in content-wind, is that the scroll starts when the next page has yet to be mounted

2022-06-22 07:46 UTC, axelthat commented
Any updates?

2022-06-22 11:33 UTC, joel-wenzel commented
> Any updates?

I am waiting until I hear from the core team before fixing merge conflicts. I have fixed them 3 or 4 times now only to become outdated again

2022-06-22 15:32 UTC, posva commented on packages/nuxt/src/pages/runtime/page.ts
> +                      nextTick(() => nuxtApp.callHook('page:finish', routeProps.Component))
won't this trigger multiple times for nested routes? That would be problematic

2022-06-22 19:45 UTC, posva commented on packages/nuxt/src/pages/runtime/page.ts
> +                      nextTick(() => nuxtApp.callHook('page:finish', routeProps.Component))
Ah I see, it's only for root transitions :+1:

2022-06-22 22:28 UTC, joel-wenzel commented
@pi0 No worries. Should be all set now if you want to test.

2022-07-18 07:32 UTC, axelthat commented
Nuxt team, please look into this 🙏

2022-07-20 11:03 UTC, jakubM817 commented
> Nuxt team, please look into this 🙏

please too

2022-08-04 16:41 UTC, nandi95 commented
This new hook might help with this issue: https://github.com/vuejs/core/issues/5844

2022-08-17 07:09 UTC, Gyurmatag commented
When this will be merged? :O

2022-08-19 19:40 UTC, rashidpathiyil commented
Waiting for a solution.....

2022-09-16 12:37 UTC, axelthat commented
Any new updates?

2022-10-10 17:52 UTC, kemalcany commented
Hoping that this PR will find itself merged into one of the upcoming rcs soon!

2022-10-10 18:07 UTC, jiblett1000 commented
> Hoping that this PR will find itself merged into one of the upcoming rcs soon!

You can snag the one from the 'Wind' nuxt content template. Just copy the `/app/router.config.ts`.

2022-10-12 21:14 UTC, nandi95 commented on packages/nuxt/src/pages/runtime/page.ts
> +          onAfterLeave
maybe for bit of safety we could check if `onAfterLeave` was already defined so we're not overwriting it.
If defined, you could wrap that in a function where you call the defined callback and then emit the event

2022-10-13 10:47 UTC, joel-wenzel commented on packages/nuxt/src/pages/runtime/page.ts
> +          onAfterLeave
@nandi95 good thinking, added it

2022-10-19 10:39 UTC, Atinux commented on packages/nuxt/src/pages/routing/default-router.options.ts
> +      position = { left: 0, top: 0 }
Something to note here is that we may not want to `scrollToTop` if we are changing routes inside a child page.

See the reference in Nuxt 2: https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/router.scrollBehavior.js#L25-L32

2022-10-19 12:28 UTC, pi0 commented on packages/nuxt/src/pages/runtime/page.ts
> +                nextTick(() => nuxtApp.callHook('page:finish', routeProps.Component).finally(done))
Heads up @danielroe we are calling `page:finish` in nextTick by this PR

2022-10-19 12:37 UTC, pi0 commented on packages/nuxt/src/pages/routing/default-router.options.ts
> +      position = { left: 0, top: 0 }
Added a simple fix with `3ec9051b077e0ad8ae2ff8bb03bd5c3c428a65a9`. BTW thanks for reference. I think in next steps we shall also support `scrollToTop` pageMeta.

2022-10-19 12:40 UTC, pi0 approved these changes

2022-10-19 12:41 UTC, pi0 commented
Thank you so much for working on this @joel-wenzel and sorry it took long to land!

I've made a few refactors and fixes on top of your work.

2022-10-19 12:43 UTC, merged

2022-11-05 13:56 UTC, lamdinh95 commented
Hello @pi0, I've updated to rc.13 today but the scroll behaviour do not work correctly.  When I navigate back, the scroll doesn't go to the save position but it's reset instead. 
The problem cause by this line in file: packages/nuxt/src/pages/runtime/router.options.ts
`const hasTransition = to.meta.pageTransition !== false && from.meta.pageTransition !== false;`
to.meta.pageTransition was undefined so the strict equal not work in here.

2022-11-05 14:21 UTC, danielroe commented
This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.

Let me know if not.