docs: server routes streaming, configuration access, query access, etc
nuxt/framework pull request #4401
Opened 2022-04-16 19:02 UTC by maciej-jezierski

### 🔗 Linked issue

#4400

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves issue #4400. Showcase of server routing usage:
* stream
* config
* promise
* how to get query parameters

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2022-04-16 19:21 UTC, DamianGlowala requested changes

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +    api: "works",
```suggestion
    api: 'works',
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +  };
```suggestion
  }
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +});
```suggestion
})
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +export default defineEventHandler(() => "Hello World!");
```suggestion
export default defineEventHandler(() => 'Hello World!')
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +});
```suggestion
  console.log('New request: ' + event.req.url)
})
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +});
```suggestion
  event.context.auth = { user: 123 }
})
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +export default defineEventHandler(() => "Test get handler");
```suggestion
export default defineEventHandler(() => 'Test get handler')
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +export default defineEventHandler(() => "Test post handler");
```suggestion
export default defineEventHandler(() => 'Test post handler')
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +export default defineEventHandler(() => `Default foo handler`);
```suggestion
export default defineEventHandler(() => `Default foo handler`)
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +export default defineEventHandler(() => `Default api handler`);
```suggestion
export default defineEventHandler(() => `Default api handler`)
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +});
```suggestion
  const body = await useBody(event)
  return { body }
})
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +});
```suggestion
export default defineEventHandler(async (event) => {
  const query = useQuery(event)
  return { a: query.param1, b: query.param2 }
})
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +});
```suggestion
import { sendStream } from 'h3'
import fs from 'fs'

export default defineEventHandler(async (event) => {
  return sendStream(event, fs.createReadStream('/path/to/file'))
})
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +  );
```suggestion
import { send, sendError } from 'h3'
import fs from 'fs'

export default defineEventHandler(async (event) => {
    return $fetch('https://example.com', { method: 'GET', parseResponse: JSON.parse })
        .then((r) => {
            const response = { data : r.data }
            // [....]
            send(event, response)
        })
        .catch(ex => sendError(event, ex))
  )
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +});
```suggestion
import { useRuntimeConfig } from '#nitro'

const config = useRuntimeConfig()

export default defineEventHandler(async (event) => {
  return { key: config.KEY }
})
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +});
```suggestion
  const cookies = useCookies(event)
  return { cookies }
})
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +import { createRouter } from "h3";
```suggestion
import { createRouter } from 'h3'
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +const router = createRouter();
```suggestion
const router = createRouter()
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +router.get("/", () => "Hello World");
```suggestion
router.get('/', () => 'Hello World')
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +export default router;
```suggestion
export default router
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +};
```suggestion
  res.end('Legacy handler')
}
```

2022-04-16 19:21 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +};
```suggestion
  console.log('Legacy middleware')
  next()
}
```

2022-04-16 19:27 UTC, DamianGlowala commented
Hi @maciej-jezierski, FYI documentation neither uses semicolons, nor double quotes (for wrapping strings in JS/TS code snippets). It might have been the linter you're using that changed them all. Good to keep an eye on it for the future PRs.

You have also got some async functions without an await keyword in the body - is it intentional or shall these be removed?

2022-04-16 20:12 UTC, maciej-jezierski commented
Hi @DamianGlowala , thanks for review. Indeed I didn't notice I had prettier plugin enabled. All not necessary changes are rolled back now and rest of the code is conducted to this standard. I also removed not necessary async keyword (functions were copied from bigger project..)

2022-04-16 20:16 UTC, DamianGlowala commented
Looks great! I'll leave the technical review to people who know this stuff better :) My very last suggestion would be to make the code indentation the same across all of the code snippets (2 spaces). Some of these appear to have 4.

2022-04-16 20:34 UTC, DamianGlowala commented on docs/content/2.guide/2.features/9.server-routes.md
> +  )
```suggestion
  return $fetch('https://example.com', { method: 'GET', parseResponse: JSON.parse })
    .then((res) => {
      const response = { data : res.data }
      // ...
      send(event, response)
    })
    .catch(err => sendError(event, err))
  )
```

2022-04-17 10:33 UTC, pi0 commented on docs/content/2.guide/2.features/9.server-routes.md
> +  return sendStream(event, fs.createReadStream('/path/to/file'))
We shall move this section to the last, mention it is only available for Node.js and with experimental support. Internal calls will be stock currently with `sendStrsm`!

2022-04-17 10:34 UTC, pi0 commented on docs/content/2.guide/2.features/9.server-routes.md
> +  return $fetch('https://example.com', { method: 'GET', parseResponse: JSON.parse })
Nitro will directly support Proxy. This is probably not a good practice to mention in examples...

2022-04-17 10:35 UTC, pi0 commented on docs/content/2.guide/2.features/9.server-routes.md
> +import { useRuntimeConfig } from '#nitro'
This can be removed we have auto import support

2022-04-17 10:35 UTC, pi0 commented on docs/content/2.guide/2.features/9.server-routes.md
> +const config = useRuntimeConfig()
Config access should be _within handler_ not global context. This is why it is a function to be always fresh.

2022-04-18 12:07 UTC, Atinux commented on docs/content/2.guide/2.features/9.server-routes.md
> +import { send, sendError } from 'h3'
Are the import needed here @pi0 ?

2022-04-18 12:34 UTC, DamianGlowala commented
Just by looking at this PR, I'd suggest an idea of standardising the casing for the section headlines across the whole documentation, as there's currently a healthy mix of both. Given the example of this section alone, we got both pascal case headlines and these which only begin with uppercase. _'Handling Requests with Body'_ next to _'Using a nested router'_ looks a bit odd.

![image](https://user-images.githubusercontent.com/48835293/163806787-aeb02d53-f97e-4848-807b-e8e14c3617b4.png)

2022-04-19 07:24 UTC, pi0 commented on docs/content/2.guide/2.features/9.server-routes.md
> +import { send, sendError } from 'h3'
No. Also no need to use either. Returning response implies sending it and `throw` sends an error + stops the handler process.

2022-04-20 11:05 UTC, Atinux commented
By looking at other places, you can remove the uppercase expect on the first word or acronyms.

2022-04-22 15:45 UTC, pi0 commented on docs/content/2.guide/2.features/9.server-routes.md
> +import { send, sendError } from 'h3'
I think just removing it. We don't need either send or sendError.

2022-04-22 15:54 UTC, pi0 commented
Good point @maciej-jezierski I think we can move them to usage examples:

<img width="214" alt="image" src="https://user-images.githubusercontent.com/5158436/164750215-dbea10a8-83a5-47f9-bab8-112de5de8307.png">

BTW this page is getting more like an API reference. We need to find a way to auto generate utils with each example to API section.

2022-04-22 16:11 UTC, merged

2022-04-22 16:11 UTC, pi0 commented
Thanks for the PR @maciej-jezierski 👍🏼