docs(features): completes assets page
nuxt/framework pull request #4563
Opened 2022-04-24 08:58 UTC by clemcode

### 🔗 Linked issue

#4104 

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR completes the `guide/features/assets` page of the documentation.

2022-04-24 08:59 UTC, Atinux commented on docs/content/2.guide/2.features/3.assets.md
> +- The `assets/` directory contains every asset that you want the build tool (Vite or Webpack) to process.
Can we link to the assets directory here?

2022-04-24 08:59 UTC, Atinux commented on docs/content/2.guide/2.features/3.assets.md
> +- The `public/` directory content is served at the server root as-is.
Can we link to the public dir as well?

2022-04-24 13:16 UTC, DamianGlowala requested changes

2022-04-24 13:16 UTC, DamianGlowala commented on docs/content/2.guide/2.features/3.assets.md
> +The `public/` directory is used as a public server for every asset that build tools don't need to process. This includes files where names can't be changed, for example `robots.txt`, or that you want
```suggestion
The `public/` directory is used as a public server for static assets that build tools don't need to process. This includes files whose names cannot be changed (for example `robots.txt`), or the ones you want to be publicly available at a defined URL of your application.
```

2022-04-24 13:16 UTC, DamianGlowala commented on docs/content/2.guide/2.features/3.assets.md
> +Nuxt can be configured to use a different name for this directory in the [`nuxt.config` file](/api/configuration/nuxt.config#public)
```suggestion
Nuxt can be configured to use a different name for this directory in the [`nuxt.config` file](/api/configuration/nuxt.config#public).
```

2022-04-25 09:44 UTC, pi0 commented on docs/content/2.guide/2.features/3.assets.md
> +Nuxt uses Vite or Webpack to build and bundle your application. The main function of these build tools is to process JavaScript files, but they can be extended through [plugins](https://vitejs.dev/pl
```suggestion
Nuxt uses [Vite](https://vitejs.dev/guide/assets.html) or [Webpack](https://webpack.js.org/guides/asset-management/) to build and bundle your application. The main function of these build tools is to process JavaScript files, but they can be extended through [plugins](https://vitejs.dev/plugins/) (for Vite) or [loaders](https://webpack.js.org/loaders/) (for Webpack) to process other kind of assets, like stylesheets, fonts or SVG. This step transforms the original file mainly for performance or caching purposes (such as stylesheets minification or browser cache invalidation).
```

2022-04-25 09:45 UTC, pi0 commented on docs/content/2.guide/2.features/3.assets.md
> +In your application's code, you can reference a file located in the `assets/` directory by using the `~/assets/` path or `assets/` alias.
Let's not advocate for ambiguous route (`assets/`)

```suggestion
In your application's code, you can reference a file located in the `assets/` directory by using the `~/assets/` path.
```

2022-04-25 09:46 UTC, pi0 commented on docs/content/2.guide/2.features/3.assets.md
> +## `public/` directory
I would move this section above assets. Seems more easier to understand and then we can continue with assets and why bundling and hashing is sometimes better

2022-04-25 09:46 UTC, pi0 commented on docs/content/2.guide/2.features/3.assets.md
> +The `public/` directory is used as a public server for static assets that build tools don't need to process. This includes files whose names cannot be changed (for example `robots.txt`), or the ones
(we can link to directory structure section)

2022-04-25 09:48 UTC, pi0 commented on docs/content/2.guide/2.features/3.assets.md
> +- The [`assets/` directory](/guide/directory-structure/assets) contains every asset that you want the build tool (Vite or Webpack) to process.
(the fact is, `assets/` is mostly convention for where to put assets not an auto scanned dir by nuxt. i wish we could little bit make it clear that other directories can be used)

2022-04-25 13:29 UTC, clemcode commented on docs/content/2.guide/2.features/3.assets.md
> +- The [`assets/` directory](/guide/directory-structure/assets) contains every asset that you want the build tool (Vite or Webpack) to process.
Thinking about this, I think we might switch the two sections, starting with `public/` : 
1. `public/` directory, the static server
2. `assets/` directory, the **convention** for files that you want processed and not served as-is.

what do you think?

2022-04-25 13:37 UTC, clemcode commented on docs/content/2.guide/2.features/3.assets.md
> +## `public/` directory
Great point, so much easier indeed.

2022-04-26 14:49 UTC, Atinux approved these changes
Happy to merge and iterate later on if needed!

2022-04-27 16:19 UTC, pi0 approved these changes

2022-04-27 16:21 UTC, merged