docs: Fix some minor typos
nuxt/framework pull request #4603
Opened 2022-04-25 19:21 UTC by dantownsend

### 🔗 Linked issue

N/A

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

While going through the Nuxt 3 docs today I came across a few minor typos.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2022-04-25 21:58 UTC, DamianGlowala requested changes

2022-04-25 21:58 UTC, DamianGlowala commented on docs/content/2.guide/1.concepts/3.rendering.md
> +Both the Browser and Server can interpret JavaScript code to render Vue.js components into HTML elements. This step is called **rendering**. Nuxt supports both **client-side** and **universal** rende
```suggestion
Both the browser and server can interpret JavaScript code to render Vue.js components into HTML elements. This step is called **rendering**. Nuxt supports both **client-side** and **universal** rendering. The two approaches have pros and cons that we will cover in this section.
```

2022-04-25 21:58 UTC, DamianGlowala commented on docs/content/2.guide/1.concepts/3.rendering.md
> +- **Performance**: The user has to wait for the browser to download, parse and run JavaScript files. Depending on the network for the download part and the user's device for the parsing and execution
```suggestion
- **Performance**: The user has to wait for the browser to download, parse and run JavaScript files. Depending on the network for the download part and the user's device for the parsing and execution, this can take some time and impact the user's experience.
```

2022-04-25 21:58 UTC, DamianGlowala commented on docs/content/2.guide/1.concepts/3.rendering.md
>  - **Search Engine Optimization**: Indexing and updating the content delivered via client-side rendering takes more time than an HTML document already built. This is related to the performance drawbac
```suggestion
- **Search Engine Optimization**: Indexing and updating the content delivered via client-side rendering takes more time than an already built HTML document. This is related to the performance drawback we discussed, as search engine crawlers won't wait for the interface to be fully rendered on their first try to index the page. Your content will take more time to show and update in search results pages with pure client-side rendering.
```

2022-04-25 21:58 UTC, DamianGlowala commented on docs/content/2.guide/1.concepts/2.vuejs-development.md
>  Nuxt 3 is based on Vue 3. The new Vue major version introduces several changes that Nuxt takes advantage of:
```suggestion
Nuxt 3 is based on Vue 3. The new major Vue version introduces several changes that Nuxt takes advantage of:
```

2022-04-25 21:58 UTC, DamianGlowala commented on docs/content/2.guide/1.concepts/2.vuejs-development.md
> +The Vue Virtual DOM (VDOM) has been rewritten from the ground up and allows for better rendering performance. On top of that, when working with compiled Single-File components, the Vue compiler can f
```suggestion
The Vue Virtual DOM (VDOM) has been rewritten from the ground up and allows for better rendering performance. On top of that, when working with compiled Single-File Components, the Vue compiler can further optimize them at build time by separating static and dynamic markup.
```

2022-04-26 05:51 UTC, dantownsend commented
@DamianGlowala Thanks for the suggestions 👍

2022-04-26 10:04 UTC, danielroe reviewed
Thanks!

2022-04-26 10:04 UTC, danielroe commented on docs/content/2.guide/1.concepts/2.vuejs-development.md
> +The Vue Virtual DOM (VDOM) has been rewritten from the ground up and allows for better rendering performance. On top of that, when working with compiled Single-File Components, the Vue compiler can f
```suggestion
The Vue Virtual DOM (VDOM) has been rewritten from the ground up and allows for better rendering performance. On top of that, when working with compiled Single File Components, the Vue compiler can further optimize them at build time by separating static and dynamic markup.
```

2022-04-26 10:04 UTC, danielroe commented on docs/content/2.guide/1.concepts/3.rendering.md
> +- **Search Engine Optimization**: Indexing and updating the content delivered via client-side rendering takes more time than an already built HTML document. This is related to the performance drawbac
```suggestion
- **Search Engine Optimization**: Indexing and updating the content delivered via client-side rendering takes more time than with a server-rendered HTML document. This is related to the performance drawback we discussed, as search engine crawlers won't wait for the interface to be fully rendered on their first try to index the page. Your content will take more time to show and update in search results pages with pure client-side rendering.
```

2022-04-26 10:06 UTC, danielroe approved these changes

2022-04-26 10:15 UTC, pi0 commented on docs/content/2.guide/1.concepts/3.rendering.md
> -- **Performance**: The user has to wait for the browser to download, parse and run javascript files. Depending on the network for the download part and the user's device for the parsing and execution
@antfu Shouldn't case-police have caught this?

2022-04-26 10:15 UTC, pi0 commented
Thanks all 💚

2022-04-26 10:15 UTC, merged

2022-04-26 10:33 UTC, DamianGlowala commented on docs/content/2.guide/1.concepts/2.vuejs-development.md
> +The Vue Virtual DOM (VDOM) has been rewritten from the ground up and allows for better rendering performance. On top of that, when working with compiled Single-File Components, the Vue compiler can f
According to the Vue 3 docs:
![image](https://user-images.githubusercontent.com/48835293/165281270-7d01a096-5a67-4b2f-973d-408a0bf025b4.png)

2022-04-26 10:34 UTC, danielroe commented on docs/content/2.guide/1.concepts/2.vuejs-development.md
> +The Vue Virtual DOM (VDOM) has been rewritten from the ground up and allows for better rendering performance. On top of that, when working with compiled Single-File Components, the Vue compiler can f
You're quite right! 🤦‍♂️