docs: Use `runtimeConfig` in migration guide
nuxt/framework pull request #4642
Opened 2022-04-26 18:54 UTC by tobiasdiez

### 🔗 Linked issue

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

The migration guide still mentioned the deprecated `publicRuntimeConfig` and `privateRuntimeConfig`, this is changed to the new `runtimeConfig`.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2022-04-26 20:52 UTC, DamianGlowala requested changes

2022-04-26 20:52 UTC, DamianGlowala commented on docs/content/migration/8.runtime-config.md
> +1. Add any environment variables you use in your app to `runtimeConfig` in `nuxt.config.ts`.
```suggestion
1. Add any environment variables that you use in your app to the `runtimeConfig` property of the `nuxt.config` file.
```

2022-04-26 20:52 UTC, DamianGlowala commented on docs/content/migration/8.runtime-config.md
> +    secretKey: '', // variable that can only be accessed on server-side
```suggestion
    secretKey: '', // variable that can only be accessed on the server side
```

2022-04-26 20:52 UTC, DamianGlowala commented on docs/content/migration/8.runtime-config.md
> +      BASE_URL: process.env.BASE_URL || 'https://nuxtjs.org' // variable that can also be accessed on the client-side
```suggestion
      BASE_URL: process.env.BASE_URL || 'https://nuxtjs.org' // variable that can also be accessed on the client side
```

2022-04-27 09:05 UTC, merged

2022-04-27 09:05 UTC, pi0 commented
Thanks @tobiasdiez @DamianGlowala