fix(nuxi): add warnings when NODE_ENV is overridden by user
nuxt/framework pull request #5417
Opened 2022-06-11 13:27 UTC by danielroe

### 🔗 Linked issue

resolves #5196

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds warnings if user is overriding the correct NODE_ENV for build/dev/analyze. (Other commands like preview, typecheck or prepare I felt did not particularly matter, but happy to expand the warnings.)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2022-06-11 22:58 UTC, DamianGlowala requested changes

2022-06-11 22:58 UTC, DamianGlowala commented on packages/nuxi/src/commands/build.ts
> +      console.warn(`Building nuxt in \`${process.env.NODE_ENV}\` mode. This is not recommended.`)
```suggestion
      console.warn(`Building Nuxt in \`${process.env.NODE_ENV}\` mode. This is not recommended.`)
```

2022-06-11 22:58 UTC, DamianGlowala commented on packages/nuxi/src/commands/analyze.ts
> +      console.warn(`Building nuxt for analysis in \`${process.env.NODE_ENV}\` mode. This is not recommended.`)
```suggestion
      console.warn(`Building Nuxt for analysis in \`${process.env.NODE_ENV}\` mode. This is not recommended.`)
```

2022-06-12 19:48 UTC, pi0 commented
Thanks for the PR but if we are not recommending custom NODE_ENV, there is no reason to allow overriding it I think. However, it is also worth tracking down what happens with custom env specially for non development builds. It can be simply one or two bugs.

2022-06-12 20:42 UTC, danielroe commented
The cause of https://github.com/nuxt/framework/issues/5196 is really a Vite bug (or perhaps it's unfair to say that it's a bug - we could say that Vite does not support _building_ in development mode). Here's how it happens:

1. `options.dev` is set to true if `NODE_ENV` is overridden
2. vitejs/plugin-vue injects HMR code because it's not production: https://github.com/vitejs/vite/blob/main/packages/plugin-vue/src/main.ts#L131-L139
3. vite replaces `import.meta.hot` with `false` because we're building: https://github.dev/vitejs/vite/blob/main/packages/vite/src/node/plugins/define.ts#L32-L45

I would be very happy with _not_ allowing `NODE_ENV` to be overridden, but think if we do then we should definitely warn. What was the reason you originally added it (https://github.com/nuxt/framework/commit/586709a82d7ce45d7cbd528bb7ee002dccae5611)?

2022-06-12 20:53 UTC, pi0 commented
Thanks for explaining! I think we can then change the strategy to override to what we expect but also warn if user already set a `NODE_ENV` we are overriding and saying hay, we just ignored your env ?

2022-06-12 21:07 UTC, pi0 commented on packages/nuxi/src/commands/analyze.ts
> +      console.info('Setting NODE_ENV to `production`.')
Can we please use a warning and also show the user-provided value that is being ignored?

2022-06-12 21:08 UTC, pi0 commented on packages/nuxi/src/commands/analyze.ts
> +      console.info('Setting NODE_ENV to `production`.')
(this can be refactored to a common utility too I guess now)

2022-06-12 21:22 UTC, pi0 commented on packages/nuxi/src/utils/env.ts
> +    console.warn(`Changing NODE_ENV from \`${currentEnv}\` to \`${targetEnv}\`.`)
```suggestion
    console.warn(`Changing \`NODE_ENV\` from \`${currentEnv}\` to \`${targetEnv}\`.`)
```

2022-06-12 21:23 UTC, pi0 approved these changes

2022-06-12 21:26 UTC, merged