docs: update navigateTo utils API page
nuxt/framework pull request #5701
Opened 2022-07-03 14:54 UTC by Krutie

### 🔗 Linked issue https://github.com/nuxt/framework/issues/4104

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Added API documentation for `navigateTo` utility function

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2022-07-03 19:42 UTC, Atinux commented on docs/content/3.api/3.utils/navigate-to.md
> +    function navigate(){
I think the function here is not necessary

2022-07-03 23:13 UTC, Krutie commented on docs/content/3.api/3.utils/navigate-to.md
> +    function navigate(){
✅ Fixed

2022-07-04 00:31 UTC, Atinux commented on docs/content/3.api/3.utils/navigate-to.md
> +    // string
I think we can remove the spaces / indentation inside the <script>

2022-07-04 00:37 UTC, Krutie commented on docs/content/3.api/3.utils/navigate-to.md
> +    // string
✅ Fixed

2022-07-04 00:54 UTC, Atinux approved these changes

2022-07-04 08:33 UTC, DamianGlowala requested changes

2022-07-04 08:33 UTC, DamianGlowala commented on docs/content/3.api/3.utils/navigate-to.md
> +This behaviour can be changed by setting `replace` to `true`, to indicate that given route should be replaced.
```suggestion
This behavior can be changed by setting `replace` to `true`, to indicate that given route should be replaced.
```

2022-07-04 08:33 UTC, DamianGlowala commented on docs/content/3.api/3.utils/navigate-to.md
> +By default, `navigateTo` pushes the given route into Vue router instance on.
_into Vue router instance on_ (?)

2022-07-04 13:10 UTC, Krutie commented on docs/content/3.api/3.utils/navigate-to.md
> +This behaviour can be changed by setting `replace` to `true`, to indicate that given route should be replaced.
✅ Fixed

2022-07-07 18:47 UTC, pi0 approved these changes
Thanks <3

2022-07-07 18:48 UTC, merged