feat(nuxt): add `fetchpriority` attribute and literal typings for meta components
nuxt/framework pull request #6251
Opened 2022-07-29 19:41 UTC by sanjaiyan-dev

Added fetchpriority attr in script and link component.

2022-07-29 22:45 UTC, danielroe approved these changes

2022-07-30 10:12 UTC, DamianGlowala commented
Shall we narrow down the accepted values for the `fetchpriority` attribute, as per https://wicg.github.io/priority-hints/#definitions?

2022-07-30 14:27 UTC, DamianGlowala requested changes

2022-07-30 14:27 UTC, DamianGlowala commented on packages/nuxt/src/head/runtime/components.ts
> +    fetchpriority: String,
https://wicg.github.io/priority-hints/#definitions
```
type FetchPriority = 'high' | 'low' | 'auto'
```

```suggestion
    fetchpriority: String as PropType<FetchPriority>,
```

2022-07-30 14:27 UTC, DamianGlowala commented on packages/nuxt/src/head/runtime/components.ts
> +    fetchpriority: String,
```suggestion
    fetchpriority: String as PropType<FetchPriority>,
```

2022-07-30 19:10 UTC, DamianGlowala commented
Great enhancement! I have closed #6262 in favor of your changes. There are two remarks that I've got:

- Why is boolean accepted for `crossorigin`? Some counterexamples:
    - https://github.com/posthtml/htmlnano/pull/79
    - https://github.com/nuxt/vue-meta/issues/447
- `x-ua-compatible` appears to be missing in `httpEquiv`, as per https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-http-equiv.

2022-07-31 08:51 UTC, DamianGlowala commented
All I am thinking is whether the following would be preferable:

```
crossorigin: String as PropType<CrossOrigin>
```

Let's wait for others to express their thoughts, not sure which way to go :)

2022-08-01 05:22 UTC, DamianGlowala commented on packages/nuxt/src/head/runtime/components.ts
> +    target: String as PropType<Targets>,
I think you meant `Target` (singular form) 👀

2022-08-01 11:40 UTC, danielroe commented on packages/nuxt/src/head/runtime/components.ts
> +} from "./types.ts";
Love the direction of this PR. Would you revert the various style/lint changes that have been made by your IDE?

2022-08-01 11:40 UTC, danielroe requested changes
Love the direction of this PR. Would you revert the various style/lint changes that have been made by your IDE?

2022-08-01 15:59 UTC, sanjaiyan-dev commented
Made suggested change (not sure) 😄

2022-08-02 11:59 UTC, danielroe commented on packages/nuxt/src/head/runtime/types.ts
> +  | string
**A note** - no autocompletion will be provided for `LinkRelationship` and `Target` as providing `string` as a type effectively removes the string literal types.

2022-08-02 12:00 UTC, danielroe approved these changes
Really nice enhancement - thanks! ❤️

2022-08-02 12:00 UTC, pi0 commented on packages/nuxt/src/head/runtime/types.ts
> +  | string
Does it makes sense to keep the types then?

2022-08-02 12:01 UTC, danielroe commented on packages/nuxt/src/head/runtime/types.ts
> +  | string
Yes, we could equally remove them without changing user experience.

2022-08-02 12:02 UTC, danielroe commented on packages/nuxt/src/head/runtime/types.ts
> +  | string
Okay - small change keeps the autocompletion 👍

2022-08-02 12:07 UTC, pi0 approved these changes
Thanks!

2022-08-02 12:08 UTC, merged

2022-08-02 12:09 UTC, sanjaiyan-dev commented
> Thanks!

My pleasure 💪🙌

2022-08-02 12:32 UTC, DamianGlowala commented on packages/nuxt/src/head/runtime/types.ts
> +  | string
Nice one! An interesting approach to preserve autocompletion by treating the `(string & {})` as 'distinguishable' :) As a fun fact, it's also covered by the `LiteralUnion` type in the `type-fest` lib:

https://github.com/sindresorhus/type-fest/blob/main/source/literal-union.d.ts