docs(api): add NuxtLayout component docs
nuxt/framework pull request #6264
Opened 2022-07-30 17:47 UTC by Krutie

### 🔗 Linked issue https://github.com/nuxt/framework/issues/4104

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Added API documentation for `NuxtLayout` component

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2022-07-30 19:45 UTC, DamianGlowala requested changes

2022-07-30 19:45 UTC, DamianGlowala commented on docs/content/3.api/2.components/2.nuxt-layout.md
> +You can use `<NuxtLayout/>` component to activate `default` layout on `app.vue` or `error.vue` .
```suggestion
You can use `<NuxtLayout />` component to activate `default` layout on `app.vue` or `error.vue`.
```

2022-07-30 19:45 UTC, DamianGlowala commented on docs/content/3.api/2.components/2.nuxt-layout.md
> +`<NuxtLayout />` is also used to override `default` layout on `app.vue` , `error.vue` or even page components found in the `/pages` directory.
```suggestion
`<NuxtLayout />` can also be used to override `default` layout on `app.vue`, `error.vue` or even page components found in the `/pages` directory.
```

2022-07-30 19:45 UTC, DamianGlowala commented on docs/content/3.api/2.components/2.nuxt-layout.md
> +## `name` props
```suggestion
## `name` prop
```

2022-07-30 19:45 UTC, DamianGlowala commented on docs/content/3.api/2.components/2.nuxt-layout.md
> +`<NuxtLayout/>` component accepts `name` property to pass the name of the custom layout. You can pass `name` props to override the default layout, where `name` can be a static string, reactive refere
```suggestion
`<NuxtLayout />` component accepts the `name` prop, which you can pass to use a non-default layout, where `name` can be a static string, reactive reference or a computed property. It **must** match the name of the corresponding layout file in the `/layouts` directory.
```

2022-07-30 19:45 UTC, DamianGlowala commented on docs/content/3.api/2.components/2.nuxt-layout.md
> +const layout = "custom";
```suggestion
const layout = 'custom'
```

2022-07-30 19:45 UTC, DamianGlowala commented on docs/content/3.api/2.components/2.nuxt-layout.md
> +```
```suggestion
::alert{icon=👉}
Please note the layout name is normalized to kebab-case, so if your layout file is named `errorLayout.vue`, it will become `error-layout` when passed as a `name` property to `<NuxtLayout />`.

```vue [/error.vue]
<template>
  <NuxtLayout :name="error-layout">
    <NuxtPage />
  </NuxtLayout>
</template>
```
::
```

2022-07-30 19:45 UTC, DamianGlowala commented on docs/content/3.api/2.components/2.nuxt-layout.md
> +`<NuxtLayout />` renders incoming content via `<slots />`. This incoming content is then wrapped around Vue’s `Transition` component to activate layout transition. For this layout transition to work
```suggestion
`<NuxtLayout />` renders incoming content via `<slot />`, which is then wrapped around Vue’s `<Transition />` component to activate layout transition. For this to work as expected, it is recommended that `<NuxtLayout />` is **not** the root element of the page component.
```

2022-08-02 13:43 UTC, pi0 approved these changes
Thanks 💯

2022-08-02 13:43 UTC, merged