docs(schema): grammar, punctuation and typo fixes
nuxt/framework pull request #6469
Opened 2022-08-09 19:44 UTC by timursaurus

### 🔗 Linked issue

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2022-08-10 06:56 UTC, DamianGlowala requested changes

2022-08-10 06:56 UTC, DamianGlowala commented on packages/schema/src/config/_app.ts
> +   * The path to a template HTML file for rendering Nuxt responses.
```suggestion
   * The path to an HTML template file for rendering Nuxt responses.
```

2022-08-10 06:56 UTC, DamianGlowala commented on packages/schema/src/config/_app.ts
> +   * Uses `<srcDir>/app.html` if it exists, or the Nuxt default template if not.
```suggestion
   * Uses `<srcDir>/app.html` if it exists, or the Nuxt's default template if not.
```

2022-08-10 06:56 UTC, DamianGlowala commented on packages/schema/src/config/_app.ts
>     * Enable or disable vuex store.
```suggestion
   * Enable or disable Vuex store.
```

2022-08-10 06:56 UTC, DamianGlowala commented on packages/schema/src/config/_common.ts
>     * server side environment variables.
```suggestion
   * server-side environment variables.
```

2022-08-10 06:56 UTC, DamianGlowala commented on packages/schema/src/config/experimental.ts
> +     * Use vite-node for on-demand server chunk loading.
```suggestion
     * Use `vite-node` for on-demand server chunk loading.
```

2022-08-10 06:56 UTC, DamianGlowala commented on packages/schema/src/config/nitro.ts
> +   * Nitro devevelopment-only server handlers.
```suggestion
   * Nitro development-only server handlers.
```

2022-08-10 06:56 UTC, DamianGlowala commented on packages/schema/src/config/render.ts
>     * This can be useful to dynamically enable/disable SSR on runtime after image builds
```suggestion
   * This can be useful to dynamically enable/disable SSR at runtime after image builds
```

2022-08-10 06:56 UTC, DamianGlowala commented on packages/schema/src/config/render.ts
>      /** Set to true to enable HTTP2 push headers */
```suggestion
    /** Set to true to enable HTTP2 push headers. */
```

2022-08-10 06:56 UTC, DamianGlowala commented on packages/schema/src/config/router.ts
> +   * Additional options passed to vue-router.
```suggestion
   * Additional options passed to `vue-router`.
```

2022-08-10 06:56 UTC, DamianGlowala commented on packages/schema/src/config/webpack.ts
> +     * Enables CSS source map support (defaults to true in development).
```suggestion
     * Enables CSS source map support (defaults to `true` in development).
```

2022-08-10 07:28 UTC, DamianGlowala commented on packages/schema/src/config/experimental.ts
> +     * Use vite-node for on-demand server chunk loading.
Consistency; same way library names are wrapped e.g. here:

```
Externalize `vue`, `@vue/*` and `vue-router` when building.
```

2022-08-10 07:30 UTC, DamianGlowala commented on packages/schema/src/config/_app.ts
> +   * The path to a template HTML file for rendering Nuxt responses.
Same word order as in:

```
or a path to an HTML template of the indicator source code (in this case,
```

2022-08-10 08:20 UTC, danielroe commented on packages/schema/src/config/webpack.ts
> +      /** Set minimize to `false` to disable all minimizers (It is disabled in development by default). */
```suggestion
      /** Set minimize to `false` to disable all minimizers. (It is disabled in development by default). */
```

2022-08-10 08:23 UTC, danielroe approved these changes
Lots of painstaking work - thank you! ❤️

2022-08-11 21:25 UTC, pi0 approved these changes
Thanks <3

2022-08-11 21:25 UTC, merged