docs(api): add useNuxtApp composable docs
nuxt/framework pull request #6786
Opened 2022-08-19 15:25 UTC by Krutie

### 🔗 Linked issue https://github.com/nuxt/framework/issues/4104

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Added API documentation for `useNuxtApp` composable

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2022-08-21 13:54 UTC, qin-guan commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +```
Perhaps this (and others below) could use the `vue` highlighting instead of `jsx`, since it is used across the documentation code examples?

2022-08-22 08:14 UTC, Krutie commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +```
✅ Fixed

2022-08-22 10:44 UTC, DamianGlowala requested changes

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +`useNuxtApp` is a built-in composable that provides a shared runtime context. This runtime context is available on both client-side and server-side and it helps you access the Vue instance, runtime h
```suggestion
`useNuxtApp` is a built-in composable that provides a shared runtime context, which is available on both client and server side. It helps you access the Vue instance, runtime hooks, runtime config variables and internal states, such as `ssrContext` and `payload`.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +You can use `useNuxtApp` within composable, plugins and components.
```suggestion
You can use `useNuxtApp` within composables, plugins and components.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +  const nuxtApp = useNuxtApp();
```suggestion
  const nuxtApp = useNuxtApp()
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +`useNuxtApp` will expose the following properties that you can use to extend and customize your app and share state, data and variables.
```suggestion
`useNuxtApp` exposes the following properties that you can use to extend and customize your app and share state, data and variables.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +`globalName` allows you to customize the global ID used in the main HTML template as well as the main Vue instance name and other options.
```suggestion
`globalName` allows you to customize the global ID used in the main HTML template, as well as the main Vue instance name and other options.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +  const nuxtApp = useNuxtApp();
```suggestion
  const nuxtApp = useNuxtApp()
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +
```suggestion
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +`ssrContext` is generated using runtime `vue-bundle-renderer` for Vue 3 and it is only available on the server-side. Nuxt exposes the following properties through `ssrContext`.
```suggestion
`ssrContext` is generated using runtime `vue-bundle-renderer` for Vue 3 and it is only available on the server side. Nuxt exposes the following properties through `ssrContext`:
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +- **event** - `type: HTTP request` - `event` allows access to `res` and `res` object for the current request made to Nuxt page
```suggestion
- **event** - `type: HTTP request` - `event` allows access to `req` and `res` objects for the current request made to the Nuxt page
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +- **runtimeConfig** - `type: runtimeConfig object` - `runtimeConfig` exposes runtime config on the client-side via payload
```suggestion
- **runtimeConfig** - `type: runtimeConfig object` - `runtimeConfig` exposes runtime config on the client side via payload
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +- **renderMeta** - `type: NuxtMeta` - returns a `Promise` of `NuxtMeta` type that includes HTML, head and body attributes as well as head tags.
```suggestion
- **renderMeta** - `type: NuxtMeta` - returns a `Promise` of `NuxtMeta` type that includes HTML, head and body attributes, as well as head tags.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +> See how the [Vue-meta plugin](https://github.com/nuxt/framework/blob/main/packages/nuxt/src/head/runtime/lib/vue-meta.plugin.ts#L23) on Nuxt uses `renderMeta` in combination with `teleports`.
```suggestion
> See how the [`vue-meta` plugin](https://github.com/nuxt/framework/blob/main/packages/nuxt/src/head/runtime/lib/vue-meta.plugin.ts#L23) in Nuxt uses `renderMeta` in combination with `teleports`.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +- **config** - exposes a `config` object that contains the configuration settings for that application.
```suggestion
- **config** - exposes a `config` object that contains the configuration settings for the application.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +- **mixins** - Applies a global `mixin` (scoped to the application). However, it is not recommended to use mixins with the Vue 3. Their sole purpose is only to provide backward compatibility.
```suggestion
- **mixins** - Applies a global `mixin` (scoped to the application). However, it is not recommended to use mixins with the Vue 3. Their sole purpose is to provide backward compatibility.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +- **provide** - Provide a value that can be injected in all descendent components within the application.
```suggestion
- **provide** - Provides a value that can be injected in all descendent components within the application.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +- **config** - exposes a `config` object that contains the configuration settings for that application.
```suggestion
- **config** - Exposes a `config` object that contains the configuration settings for that application.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +> See `use` example: [https://v3.nuxtjs.org/guide/directory-structure/plugins#vue-plugins](https://v3.nuxtjs.org/guide/directory-structure/plugins#vue-plugins)
```suggestion
> See `use` example: [https://v3.nuxtjs.org/guide/directory-structure/plugins#vue-plugins](https://v3.nuxtjs.org/guide/directory-structure/plugins#vue-plugins).
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +> See `directive` example: [https://v3.nuxtjs.org/guide/directory-structure/plugins#vue-directives](https://v3.nuxtjs.org/guide/directory-structure/plugins#vue-directives)
```suggestion
> See `directive` example: [https://v3.nuxtjs.org/guide/directory-structure/plugins#vue-directives](https://v3.nuxtjs.org/guide/directory-structure/plugins#vue-directives).
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +`nuxtApp` is a runtime context that you can extend using [Nuxt Plugins](https://v3.nuxtjs.org/guide/directory-structure/plugins). You can use the `provide` function to create Nuxt plugins to make val
```suggestion
`nuxtApp` is a runtime context that you can extend using [Nuxt plugins](https://v3.nuxtjs.org/guide/directory-structure/plugins). You can use the `provide` function to create Nuxt plugins to make values and helper methods available in your Nuxt application across all composables and components.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +As you can see in the example above, `$hello` has become the new and custom part of `nuxtApp` context and it is available at all places where `nuxtApp` is accessible.
```suggestion
As you can see in the example above, `$hello` has become the new and custom part of `nuxtApp` context and it is available in all places where `nuxtApp` is accessible.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +`nuxtApp.$config` exposes runtime-config and environment variables on the client-side to the Nuxt app context through two keys: `app` and `public`.
```suggestion
`nuxtApp.$config` exposes a runtime config and environment variables on the client side to the Nuxt app context through two keys: `app` and `public`.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +Keys found under `app` and `public` are available on the client-side.
```suggestion
Keys found under `app` and `public` are available on the client side.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +> Same `$config` object is accessible through `nuxtApp.payload.config` as well.
```suggestion
> The same `$config` object is also accessible through `nuxtApp.payload.config`.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +`payload` exposes data and state variables from server-side to client-side and make them available in the `window.NUXT` object that is accessible from the browser.
```suggestion
`payload` exposes data and state variables from server side to client side and makes them available in the `window.NUXT` object that is accessible from the browser.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +`payload` exposes following keys on client-side after they are stringified and passed from the server-side:
```suggestion
`payload` exposes the following keys on the client side after they are stringified and passed from the server side:
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +- **data** - `type: record object` - when you fetch the data from an API endpoint using either `useFetch` or `useAsyncData`, resulting payload can be accessed from the `payload.data` . This data is c
```suggestion
- **data** - `type: record object` - When you fetch the data from an API endpoint using either `useFetch` or `useAsyncData`, resulting payload can be accessed from the `payload.data`. This data is cached and helps you prevent fetching the same data in case an identical request is made more than once.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +After fetching the value of `count` using `useAsyncData` in the example above, if you access `payload.data`, you will see `{ count: 1 }` recorded there. And the value `count` is updated accordingly a
```suggestion
After fetching the value of `count` using `useAsyncData` in the example above, if you access `payload.data`, you will see `{ count: 1 }` recorded there. The value of `count` is updated whenever the page count increases.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +When accessing the same `payload.data` from [ssrcontext](#ssrcontext), you can access the same value on the server-side as well.
```suggestion
When accessing the same `payload.data` from [ssrcontext](#ssrcontext), you can access the same value on the server side as well.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +- **state** - `type: record object` - when you use `useState` composable in Nuxt to set shared state, this state data is accessed through payload.state.[name-of-your-state]
```suggestion
- **state** - `type: record object` - When you use `useState` composable in Nuxt to set shared state, this state data is accessed through `payload.state.[name-of-your-state]`.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +Hooks available in `nuxtApp` allows you to customize the runtime aspects of your Nuxt application. You can use runtime hooks in Vue composable and [Nuxt Plugins](/guide/directory-structure/plugins) t
```suggestion
Hooks available in `nuxtApp` allows you to customize the runtime aspects of your Nuxt application. You can use runtime hooks in Vue composable and [Nuxt plugins](/guide/directory-structure/plugins) to hook into the rendering lifecycle.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +`hook` function is useful for adding custom logic by hooking into the rendering lifecycle at a specific point. `hook` function is mostly used in creating Nuxt plugins.
```suggestion
`hook` function is useful for adding custom logic by hooking into the rendering lifecycle at a specific point. `hook` function is mostly used when creating Nuxt plugins.
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +  console.log('vue:error')
```suggestion
    console.log('vue:error')
```

2022-08-22 10:44 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +`callHook` returns promise when called with any of the existing hooks.
```suggestion
`callHook` returns a promise when called with any of the existing hooks.
```

2022-08-22 15:25 UTC, merged

2022-08-22 15:26 UTC, DamianGlowala commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +See [Runtime Hooks](/api/advanced/hooks#app-hooks-runtime) for avialble runtime hooks called by Nuxt.
@pi0 little typo: _avialble_

2022-08-22 15:35 UTC, pi0 commented on docs/content/3.api/1.composables/use-nuxt-app.md
> +See [Runtime Hooks](/api/advanced/hooks#app-hooks-runtime) for avialble runtime hooks called by Nuxt.
thanks for the notice. (please check your discord when could. I've sent a message)