docs: :memo: Use await instead of return
nuxt/framework pull request #7734
Opened 2022-09-21 17:58 UTC by TheDutchCoder

### 🔗 Linked issue

#7732 

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

1. Changes the `navigateTo` example to use `await` instead of return, as `return` will throw a compilation error.
2. Formats the block of code to be consistent with other blocks.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2022-09-21 18:56 UTC, DamianGlowala requested changes

2022-09-21 18:56 UTC, DamianGlowala commented on docs/content/3.api/3.utils/navigate-to.md
> +  })
Good catch! In terms of top-level indentation within the `<script setup>` block, there is currently a mix of both in the code snippets across the documentation, but I'd be in favor of no indentation. An example to back this up:

https://vuejs.org/api/sfc-script-setup.html#basic-syntax

```suggestion
// passing 'to' as a string
await navigateTo('/search')

// ... or as a route object
await navigateTo({ path: '/search' })

// ... or as a route object with query parameters
await navigateTo({
  path: '/search',
  query: {
    page: 1,
    sort: 'asc'
  }
})
```

2022-09-21 19:28 UTC, TheDutchCoder commented on docs/content/3.api/3.utils/navigate-to.md
> +  })
I personally also use unindented code, just wasn't sure which one was preferred in general and this page had both.
Made it all unindented, thanks!

2022-09-22 09:00 UTC, danielroe approved these changes
Thank you! ❤️

2022-09-22 13:23 UTC, merged