docs: add nitro hooks docs
nuxt/framework pull request #7782
Opened 2022-09-23 08:09 UTC by huang-julien

### 🔗 Linked issue
https://github.com/nuxt/framework/issues/6571

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

📖 Hi this PR document nitro hooks 📖

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2022-09-23 08:17 UTC, danielroe commented on docs/content/2.guide/4.going-further/2.hooks.md
> +These hooks are available for [Nitro Plugins](https://nitro.unjs.io/guide/advanced/plugins) to hook into nitro's runtime behavior.
```suggestion
These hooks are available for [Nitro plugins](https://nitro.unjs.io/guide/advanced/plugins) to hook into Nitro's runtime behavior.
```

2022-09-23 08:18 UTC, danielroe commented on docs/content/2.guide/4.going-further/2.hooks.md
> +### Usage with Server Plugins
```suggestion
### Usage within a Nitro Plugin
```

2022-09-23 08:18 UTC, danielroe commented on docs/content/3.api/4.advanced/1.hooks.md
> +# Nitro Hooks (runtime, server-side)
```suggestion
# Nitro App Hooks (runtime, server-side)
```

2022-09-23 08:18 UTC, danielroe commented on docs/content/2.guide/4.going-further/2.hooks.md
> +## Nitro Hooks (Runtime)
```suggestion
## Nitro App Hooks (Runtime)
```

2022-09-23 08:19 UTC, danielroe commented on docs/content/2.guide/4.going-further/2.hooks.md
> +## Nitro Hooks (Runtime)
(there are also Nitro build hooks which we can document later)

2022-09-23 08:20 UTC, danielroe commented on docs/content/2.guide/4.going-further/2.hooks.md
> +Learn more about  [available nitro lifecycle hooks](/api/advanced/hooks#nitro-hooks-runtime-server-side)
```suggestion
Learn more about [available Nitro lifecycle hooks](/api/advanced/hooks#nitro-hooks-runtime-server-side)
```

2022-09-23 08:20 UTC, danielroe approved these changes
Thank you ❤️

2022-09-23 08:45 UTC, DamianGlowala requested changes

2022-09-23 08:45 UTC, DamianGlowala commented on docs/content/2.guide/4.going-further/2.hooks.md
> +});
```suggestion
    console.log('render:html', html)
    html.bodyAppend.push('<hr>Appended by custom plugin</hr>')
  });

  nitroApp.hooks.hook('render:response', (response, { event }) => {
    console.log('render:response', response)
  })
})
```

2022-09-23 08:45 UTC, DamianGlowala commented on docs/content/2.guide/4.going-further/2.hooks.md
> +Learn more about [available Nitro lifecycle hooks](/api/advanced/hooks#nitro-hooks-runtime-server-side)
```suggestion
Learn more about available [Nitro lifecycle hooks](/api/advanced/hooks#nitro-hooks-runtime-server-side).
```

2022-09-23 08:45 UTC, DamianGlowala commented on docs/content/3.api/4.advanced/1.hooks.md
> +`render:response`      | `response, { event }` | Called before sending the response.  | [response](https://github.com/unjs/h3/blob/f6ceb5581043dc4d8b6eab91e9be4531e0c30f8e/src/types.ts#L38), [event](
(unsure whether updated URL is pointing to the right place)

```suggestion
`render:response`      | `response, { event }` | Called before sending the response.  | [response](https://github.com/nuxt/framework/blob/71ef8bd3ff207fd51c2ca18d5a8c7140476780c7/packages/nuxt/src/core/runtime/nitro/renderer.ts#L24), [event](https://github.com/unjs/h3/blob/f6ceb5581043dc4d8b6eab91e9be4531e0c30f8e/src/types.ts#L38)
```

2022-09-23 08:45 UTC, danielroe commented on docs/content/2.guide/4.going-further/2.hooks.md
> +});
`<hr>` is void and so I think it was right before...

2022-09-23 08:47 UTC, danielroe commented on docs/content/3.api/4.advanced/1.hooks.md
> +`render:response`      | `response, { event }` | Called before sending the response.  | [response](https://github.com/unjs/h3/blob/f6ceb5581043dc4d8b6eab91e9be4531e0c30f8e/src/types.ts#L38), [event](
good spot!

2022-09-23 09:39 UTC, DamianGlowala commented on docs/content/2.guide/4.going-further/2.hooks.md
> +});
🤦 ofc it is, my bad (: I mistakenly treated it as a header tag for some reason.

2022-09-25 16:16 UTC, danielroe approved these changes

2022-09-26 09:17 UTC, pi0 approved these changes
Thanks <3

2022-09-26 09:18 UTC, merged