feat(docs): Extend Theme Config
nuxt/framework pull request #9405
Opened 2022-11-29 16:48 UTC by cpreston321

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds more detail about the how to use extends since it's very powerful with little documentation we have now on this feature. I wanted to help out but hopefully this is a start to show off how nice of a feature this is. If you need modify it or change the structure on where it's located please let me know! 

Thanks 💚 

### 📝 Checklist

- [] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2022-11-29 17:54 UTC, manniL requested changes
Good start! Left some remarks

2022-11-29 17:54 UTC, manniL commented on docs/content/1.docs/1.getting-started/3.extends-theme.md
> +- `compasables/*` - Extend the default compasables
```suggestion
- `composables/*` - Extend the default composables
```

2022-11-29 17:54 UTC, manniL commented on docs/content/1.docs/1.getting-started/3.extends-theme.md
> +::list{type="success"}
Probably adding pages here would make sense too!

2022-11-29 17:54 UTC, manniL commented on docs/content/1.docs/1.getting-started/3.extends-theme.md
> +To uses extends to it's full potential. You can create a **node module** (*has to be published first) or a **repo** that contains the files you want to extend. This allows you to share your config wi
```suggestion
To uses extends to it's full potential, you can create a **node module** (*has to be published first) or a **repo** that contains the files you want to extend. This allows you to share your config with others, use it in multiple projects or use it privately.
```

2022-11-29 17:54 UTC, manniL commented on docs/content/1.docs/1.getting-started/3.extends-theme.md
> +If you want to use extends for `github:`, `bitbucket:`, `gitlab:`, `https:` you need to make sure that the repo is **public** or reachable by the user **without authentication**.
Not exactly true, you can use `GIGET_AUTH` - see https://github.com/unjs/c12/issues/50#issuecomment-1321878238

2022-11-29 17:54 UTC, manniL commented on docs/content/1.docs/1.getting-started/3.extends-theme.md
> +To use extends with a node module, you need to make sure that the module is published to npm. You can then use the module name to extend the default theme.
```suggestion
To use `extends` with a node module, you need to make sure that the module is published to npm. You can then use the module name to extend the default theme.
```

2022-11-29 18:12 UTC, cpreston321 commented on docs/content/1.docs/1.getting-started/3.extends-theme.md
> +::list{type="success"}
Done

2022-11-29 18:12 UTC, cpreston321 commented on docs/content/1.docs/1.getting-started/3.extends-theme.md
> +- `compasables/*` - Extend the default compasables
Fixed!

2022-11-29 18:13 UTC, cpreston321 commented on docs/content/1.docs/1.getting-started/3.extends-theme.md
> +To uses extends to it's full potential. You can create a **node module** (*has to be published first) or a **repo** that contains the files you want to extend. This allows you to share your config wi
Fixed!

2022-11-29 18:13 UTC, cpreston321 commented on docs/content/1.docs/1.getting-started/3.extends-theme.md
> +If you want to use extends for `github:`, `bitbucket:`, `gitlab:`, `https:` you need to make sure that the repo is **public** or reachable by the user **without authentication**.
Updated!

2022-11-29 18:16 UTC, cpreston321 commented
@manniL Updated ✅

2022-12-01 20:56 UTC, manniL approved these changes

2022-12-02 10:36 UTC, pi0 commented
Thanks for the PR @cpreston321 ❤️ 

I like to move it to Guide > Going Further > Nuxt Layers to be consistent with the starter name (https://github.com/nuxt/starter/issues/183) and generally the way we announce this feature.

What do you think @antfu @danielroe @Atinux?

2022-12-02 10:39 UTC, manniL commented
> I like to move it to Guide > Going Further > Nuxt Layers to be consistent with the starter name (https://github.com/nuxt/starter/issues/183) and generally the way we announce this feature.

We call all things we can extends `layers` then, right? (Just want to nail the terminology)

2022-12-02 10:49 UTC, pi0 commented
(working on some refactors to try splitting into user guide + author guide)

2022-12-02 11:13 UTC, Atinux commented
I agree to rename to `Extends Theme` to `Layers` or `App Layers`.

I think it's nice to keep a part in the getting started, but should not be in 3rd position but after Error Handling and before Testing since it is a bit advanced but really good to know so people can shape their Nuxt app with this feature in mind.

2022-12-02 11:15 UTC, manniL commented
Oh yes, I agree that `App Layers` or `Layers` for short is a nice term that fits pretty well 👍🏻

2022-12-02 11:33 UTC, Atinux commented
Pushed an update so it will look like this:
![CleanShot 2022-12-02 at 12.31.36@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2022_12_02_at_12_31_36_2x_51ee6148b5.png)

I think we may want to talk more about the layer feature instead of extends feature. 

Instead saying to extend a layer, use the `extends` property.

With `extends: [<layerA>, <layerB>, ...]`

2022-12-02 11:49 UTC, Tahul reviewed
Wonderful idea to finally document such an important part of Nuxt 3 :)

I would add some warnings though, that are the biggest "gotchas" for me with extending:

- Relative paths in extended `nuxt.config`, even if resolved by Nuxt, are always better rewritten with `resolve`:

```ts
import { createResolver } from '@nuxt/kit'
const { resolve: resolveLayerDir } = createResolver(import.meta.url)
export default defineNuxtConfig({
   css: [resolveLayerDir('./assets/main.css')]
})
```

- Dependencies from an NPM published layer **HAS** to be in `dependencies` and not in `devDependencies`.

- Git and other "remote" ways of extending also applies to that issue except the dependencies from the extended layers **HAS** to be in the parent layer dependencies, as this way of extending won't be going through a package manager resolving the layer as a dependency.

- Maybe add a paragraph mentioning how configuration files are merged ([**defu**](https://github.com/unjs/defu))

- Maybe add an **Advanced** section that talks about how to make your modules compatible with extends, because I'm pretty sure most modules that relies on importing anything from the user repository won't yet bet compatible with this.

---

On a side note, I think if we begin to talk about this part of Nuxt 3 in public (documentation page kind of feel like we finally release this feature to the public..), I would also urgently add an official explainer of what is the difference between **EXTENDING** and **MODULES**.

Extending allows all the same things as module, especially if we advertize it as possible through NPM.

I think it might be misleading for some package authors which method of publishing should they choose.

2022-12-02 11:49 UTC, Tahul commented on docs/content/1.docs/1.getting-started/9.layers.md
> +- [Nuxt Content Wind Theme](https://github.com/Atinux/content-wind#readme)
I would also add a link to
- https://github.com/nuxt/starter/tree/layer
- https://github.com/nuxt-themes/starter
- https://github.com/nuxt/framework/tree/main/examples/advanced/config-extends

2022-12-02 11:49 UTC, Tahul commented on docs/content/1.docs/1.getting-started/9.layers.md
> +
I would add a paragraph mentioning that for now, dependencies from the extended layer **must** be inside `dependencies` or also be installed on the parent layer.

2022-12-02 11:49 UTC, Tahul commented on docs/content/1.docs/1.getting-started/9.layers.md
> +    "description": "My Theme",
I think we add `"type": "module"` in that configuration for it to work properly with auto-imports.

2022-12-02 11:49 UTC, Tahul commented on docs/content/1.docs/1.getting-started/9.layers.md
> +If you want to use extends for `github:`, `bitbucket:`, `gitlab:` or `https:` on a private remote source, you need to add an environmen variable `GIGET_AUTH=<tokenHere>` for it to download the files.
```suggestion
If you want to use extends for `github:`, `bitbucket:`, `gitlab:` or `https:` on a private remote source, you need to add an environment variable `GIGET_AUTH=<tokenHere>` for it to download the files.
```

2022-12-02 12:29 UTC, pi0 commented on docs/content/1.docs/1.getting-started/9.layers.md
> +- [Nuxt Content Wind Theme](https://github.com/Atinux/content-wind#readme)
I've added both themes and nuxt/starter in new rewrite.

2022-12-02 12:30 UTC, pi0 commented on docs/content/1.docs/1.getting-started/9.layers.md
> +
Note added in rewrite.

2022-12-02 12:31 UTC, pi0 commented on docs/content/1.docs/1.getting-started/9.layers.md
> +    "description": "My Theme",
Can you link to issue with auto imports and type module? Generally is a good idea btw to add type.

2022-12-02 12:58 UTC, manniL commented
In addition to what @Tahul mentioned regarding "Layers vs. Modules": It is also important to keep in mind that modules are a bit more flexible due to config, switching parts on and off etc.

And that not every module should be rewritten as layer 😆

2022-12-02 13:02 UTC, Tahul commented
> In addition to what @Tahul mentioned regarding "Layers vs. Modules": It is also important to keep in mind that modules are a bit more flexible due to config, switching parts on and off etc.
> 
> And that not every module should be rewritten as layer 😆

Yet now that there is `app.config` as well, some parts of the config the used to belong in `nuxt.config` makes much more sense there.

Especially everything related to runtime/UI parts, as this config file is compatible with HMR, in opposition with nuxt.config where any change needs a full server restart.

I think a checklist of both down/up-sides of each approach would be best, and some examples of the usage we want to promote?

2022-12-02 13:21 UTC, pi0 commented
Thanks for the very nice feedback @Tahul. I tried to include any missing of them while making split. 

On modules vs layers, well basically they are individual features of Nuxt not alternatives. Modules are used to create **add-on integrations and features** that are not a built-in feature of nuxt core while layers allow reusing code built on **existing features**. I think new explanation in the starter about layer use cases should make it better but any followup PR is more than welcome to clarify usage of each.

2022-12-02 13:32 UTC, pi0 commented
Preview: 

- https://framework-p5slf61fd-nuxt-js.vercel.app/docs/getting-started/layers
- https://framework-p5slf61fd-nuxt-js.vercel.app/docs/guide/going-further/layers

I would personally move layers introduction to the concepts section based on how we introduce other features like modules but also okay for it being in getting started.

/cc @Atinux feel free to push any structure changes needed.

2022-12-02 13:33 UTC, pi0 approved these changes

2022-12-02 13:47 UTC, danielroe commented on docs/content/1.docs/2.guide/3.going-further/7.layers.md
> +Nuxt layers, are a powerful feature that you can use to share and reuse partial Nuxt applications within a monorepo or directly publish them via NPM or git repository. The layers structure is almost
```suggestion
Nuxt layers, are a powerful feature that you can use to share and reuse partial Nuxt applications within a monorepo, or from a git repository or npm package. The layers structure is almost identical to a standard Nuxt application, which makes them easy to author and maintain. ([Read More](/docs/getting-started/layers))
```

2022-12-02 13:48 UTC, danielroe commented on docs/content/1.docs/2.guide/3.going-further/7.layers.md
> +Additionally, you can create more files to extend in the layer directory. They will be auto-scanned by Nuxt and extended for the project extending this layer.
```suggestion
Additionally, certain other files in the layer directory will be auto-scanned and used by Nuxt for the project extending this layer.
```

2022-12-02 13:49 UTC, danielroe commented on docs/content/1.docs/2.guide/3.going-further/7.layers.md
> +To get started you want to init the [nuxt/starter/layer](https://github.com/nuxt/starter/tree/layer). This will create a basic structure for you to start with. Execute this command within the termina
```suggestion
To get started you can initialize a layer with the [nuxt/starter/layer template](https://github.com/nuxt/starter/tree/layer). This will create a basic structure you can build upon. Execute this command within the terminal to get started:
```

2022-12-02 13:50 UTC, danielroe commented on docs/content/1.docs/2.guide/3.going-further/7.layers.md
> +You can publish and share layers by either using a remote source or an NPM package.
```suggestion
You can publish and share layers by either using a remote source or an npm package.
```

2022-12-02 13:50 UTC, danielroe commented on docs/content/1.docs/2.guide/3.going-further/7.layers.md
> + npx nuxi init --template gh:nuxt-themes/starter my-theme
should this be:

```suggestion
 npx nuxi init --template themes/starter my-theme
```

2022-12-02 13:51 UTC, danielroe commented on docs/content/1.docs/2.guide/3.going-further/7.layers.md
> +You can use a Git repository to share your Nuxt layer. Some examples:
```suggestion
### Publishing via Git Repository

You can use a git repository to share your Nuxt layer. Some examples:
```

2022-12-02 13:51 UTC, danielroe commented on docs/content/1.docs/2.guide/3.going-further/7.layers.md
> +If you want to extend a private remote source, you need to add an environment variable `GIGET_AUTH=<token>` to provide a token.
```suggestion
If you want to extend a private remote source, you need to add the environment variable `GIGET_AUTH=<token>` to provide a token.
```

2022-12-02 13:51 UTC, danielroe commented on docs/content/1.docs/2.guide/3.going-further/7.layers.md
> +Currently, with git remote sources, if a layer has NPM dependencies, you need to manually install it in the target project. We are working on this to auto-install layer dependencies with git sources.
```suggestion
Currently, with git remote sources, if a layer has npm dependencies, you need to manually install it in the target project. We are working on this to auto-install layer dependencies with git sources.
```

2022-12-02 13:52 UTC, danielroe commented on docs/content/1.docs/2.guide/3.going-further/7.layers.md
> +To extend from an NPM package, you need to make sure that the module is published to NPM and installed in the user's project as a devDependency. Then you can use the module name to extend the current
```suggestion
You can publish Nuxt layers as an npm package that contains the files and dependencies you want to extend. This allows you to share your config with others, use it in multiple projects or use it privately.

To extend from an npm package, you need to make sure that the module is published to npm and installed in the user's project as a devDependency. Then you can use the module name to extend the current nuxt config:
```

2022-12-02 14:01 UTC, danielroe approved these changes
This is a great initiative - many thanks indeed! ❤️

2022-12-02 14:06 UTC, pi0 commented on docs/content/1.docs/2.guide/3.going-further/7.layers.md
> +import { fileURLToPath } from 'module'
```suggestion
import { fileURLToPath } from 'node:url'
```

@danielroe BTW using require was intentionally to make the workaround simpler while we need it. Jiti always support require.resolve and it is enough for this case...

2022-12-02 14:07 UTC, danielroe commented on docs/content/1.docs/2.guide/3.going-further/7.layers.md
> +import { fileURLToPath } from 'module'
I don't believe it would work with a css file?

2022-12-02 14:08 UTC, danielroe commented on docs/content/1.docs/2.guide/3.going-further/7.layers.md
> +import { fileURLToPath } from 'module'
... no, you're right, it would have worked - but I think best to avoid.

2022-12-02 14:18 UTC, cpreston321 commented
Glad to see that everyone is helping - this feature is so powerful. 

I appreciate you all 💚

2022-12-03 17:52 UTC, cpreston321 commented
related issue with nitro extends: https://github.com/nuxt/framework/issues/9384

2022-12-03 19:20 UTC, manniL commented
Also important to consider: https://github.com/nuxt/framework/discussions/9418

2022-12-04 11:27 UTC, Atinux commented on docs/content/1.docs/2.guide/3.going-further/7.layers.md
> +Currently, with git remote sources, if a layer has npm dependencies, you will need to manually install them in the target project. We are working on this to auto-install layer dependencies with git s
Could we link a GitHub issue to it?

2022-12-04 11:37 UTC, manniL commented on docs/content/1.docs/2.guide/3.going-further/7.layers.md
> +Currently, with git remote sources, if a layer has npm dependencies, you will need to manually install them in the target project. We are working on this to auto-install layer dependencies with git s
Not sure there is one yet 👀

2022-12-05 10:44 UTC, merged

2022-12-05 10:45 UTC, pi0 commented
Thanks all for helping on this 🙌 Let's iterate to improve layers support and docs.

2022-12-05 10:49 UTC, Atinux commented
Was going to push, could have wait for my approval that was coming in few minutes, anyway will push my changes directly to main 👍