feat(kit): add `extendRouteRules` method
nuxt/framework pull request #9771
Opened 2022-12-17 13:29 UTC by xtoolkit

### 🔗 Linked issue

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

In nuxt module develop with nuxt/kit, `extendRouteRules` method can be help add custom routeRules config.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2022-12-17 18:27 UTC, danielroe commented on packages/kit/src/pages.ts
> +import { NitroRouteConfig } from 'nitropack'
```suggestion
import type { NitroRouteConfig } from 'nitropack'
```

2022-12-17 18:29 UTC, danielroe commented on packages/kit/src/pages.ts
> +  nuxt.options.nitro.routeRules[route] = rule
should we merge rather than entirely overriding the rule?

2022-12-18 10:34 UTC, manniL commented on packages/kit/src/pages.ts
> +  nuxt.options.nitro.routeRules[route] = rule
I'd prefer merging too. 
But maybe we could get the current route rule object (if existing) and alter it e.g. via function?

2022-12-18 11:13 UTC, xtoolkit commented on packages/kit/src/pages.ts
> +  nuxt.options.nitro.routeRules[route] = rule
We can add option to merge rules like this:
```ts
function extendRouteRules (route: string, rule: NitroRouteConfig, merge: boolean = true)
```
or
```ts
function extendRouteRules (route: string, rule: NitroRouteConfig, override: boolean = true)
```

2022-12-19 11:43 UTC, pi0 commented on packages/kit/src/pages.ts
> +  nuxt.options.nitro.routeRules[route] = rule
`{ ovrride: true }` as 3rd param makes sense. When disabled (default) user config has priority for merging object. When enabled, it can override user config.

2022-12-19 11:44 UTC, danielroe commented on packages/kit/src/pages.ts
> +  nuxt.options.nitro.routeRules[route] = rule
Agreed 👍

2022-12-19 17:37 UTC, xtoolkit commented on packages/kit/src/pages.ts
> +  nuxt.options.nitro.routeRules[route] = rule
hi
check again please

2022-12-20 14:56 UTC, danielroe requested changes
can we support, instead of a boolean flag as third argument, an options object with an `override` property?

2022-12-20 15:40 UTC, danielroe approved these changes
Thanks! Sorry for the back-and-forth. This looks good. ❤️

2022-12-20 15:53 UTC, pi0 commented on packages/kit/src/pages.ts
> +    ? rule
I belive in override mode, we still can keep existing extra rules but give the `rule` more priority than current rules

2022-12-20 17:03 UTC, xtoolkit commented on packages/kit/src/pages.ts
> +    ? rule
Can you write a example? I did't understand!

2023-01-14 01:18 UTC, danielroe commented on packages/kit/src/pages.ts
> +    : defu(rule, nuxt.options.routeRules[route] || {})
I think this is what @pi0 is suggesting:

```suggestion
  nuxt.options.routeRules[route] = options.override
    ? defu(rule, nuxt.options.routeRules[route])
    : defu(nuxt.options.routeRules[route], rule)
```

2023-01-15 21:25 UTC, xtoolkit commented on packages/kit/src/pages.ts
> +    : defu(rule, nuxt.options.routeRules[route] || {})
I thing in this example, override doesn't mean.
I thing remove override option is better! Or I misunderstood :(

2023-01-21 14:54 UTC, danielroe commented on packages/kit/src/pages.ts
> +    ? rule
```suggestion
    ? defu(rule, nuxt.options.routeRules[route])
    : defu(nuxt.options.routeRules[route], rule)
```

2023-01-21 14:55 UTC, danielroe commented on packages/kit/src/pages.ts
> +    : defu(rule, nuxt.options.nitro.routeRules[route] || {})
```suggestion
    : defu(nuxt.options.nitro.routeRules[route], rule)
```

2023-01-21 14:57 UTC, danielroe commented on packages/kit/src/pages.ts
> +    : defu(nuxt.options.nitro.routeRules[route], rule)
feels like we could optimise slightly:

```suggestion
  for (const options of [nuxt.options, nuxt.options.nitro]) {
	  if (!options.routeRules) {
	    options.routeRules = {}
	  }
	  options.routeRules[route] = options.override
	    ? defu(rule, options.routeRules[route])
	    : defu(options.routeRules[route], rule)
  }
```

2023-01-21 16:35 UTC, pi0 approved these changes
Thanks 💯

2023-01-21 16:54 UTC, merged