Use `NuxtLayout`
nuxt/framework pull request #9854
Opened 2022-12-25 10:27 UTC by datamadsen

After introducing `layouts/default.vue`, `pages/index.vue` and `pages/about.vue` can use `<NuxtLayout>...</NuxtLayout>` to take advantage of the layout which was not in the documentation.

2022-12-25 13:08 UTC, manniL requested changes
If not "escaping" the chosen layout, one should use `NuxtLayout` in the `app.vue` instead of repeating the component in each subpage ☺️

2022-12-25 15:30 UTC, datamadsen commented
> If not "escaping" the chosen layout, one should use `NuxtLayout` in the `app.vue` instead of repeating the component in each subpage ☺️

Thanks - I removed the pages files and added a modified app.vue listing.

2023-01-08 13:15 UTC, manniL approved these changes

2023-01-09 11:22 UTC, danielroe commented on docs/content/1.docs/1.getting-started/3.views.md
> +    </NuxtLayout>
if no `app.vue` is present, then the default Nuxt `app.vue` is used, which is:

```
<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>
```

That is why it is omitted in this example.

2023-01-09 14:20 UTC, datamadsen commented on docs/content/1.docs/1.getting-started/3.views.md
> +    </NuxtLayout>
No problem. As a newcomer to nuxt and vue I was just following along in the examples and had a stumble when trying out examples in the layout section because the app.vue from an earlier example didn’t include layouts. The only reason for the pr is to try and minimize the search to an answer for why it didn’t work/how to get it to work, but it could be that it’s not really a problem so it’s fine with me to just close the pr unmerged

2023-01-10 16:06 UTC, closed without merging